//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.ProdutosImpostosReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL", ConfigurationName="ProdutosImpostosReference.ProdutosImpostosSoap")]
    public interface ProdutosImpostosSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLIncluirImposto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listaImpostos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaIncluirImpostoResponse")]
        Sync.ProdutosImpostosReference.priaIncluirImpostoResponse IncluirImposto(Sync.ProdutosImpostosReference.priaIncluirImpostoRequest priaIncluirImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLIncluirImposto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaIncluirImpostoResponse")]
        System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaIncluirImpostoResponse> IncluirImpostoAsync(Sync.ProdutosImpostosReference.priaIncluirImpostoRequest priaIncluirImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLAlterarImposto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listaImpostos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaAlterarImpostoResponse")]
        Sync.ProdutosImpostosReference.priaAlterarImpostoResponse AlterarImposto(Sync.ProdutosImpostosReference.priaAlterarImpostoRequest priaAlterarImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLAlterarImposto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaAlterarImpostoResponse")]
        System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaAlterarImpostoResponse> AlterarImpostoAsync(Sync.ProdutosImpostosReference.priaAlterarImpostoRequest priaAlterarImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLUpsertImposto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listaImpostos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaUpsertImpostoResponse")]
        Sync.ProdutosImpostosReference.priaUpsertImpostoResponse UpsertImposto(Sync.ProdutosImpostosReference.priaUpsertImpostoRequest priaUpsertImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLUpsertImposto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaUpsertImpostoResponse")]
        System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaUpsertImpostoResponse> UpsertImpostoAsync(Sync.ProdutosImpostosReference.priaUpsertImpostoRequest priaUpsertImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLExcluirImposto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listaImpostos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaExcluirImpostoResponse")]
        Sync.ProdutosImpostosReference.priaExcluirImpostoResponse ExcluirImposto(Sync.ProdutosImpostosReference.priaExcluirImpostoRequest priaExcluirImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLExcluirImposto", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaExcluirImpostoResponse")]
        System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaExcluirImpostoResponse> ExcluirImpostoAsync(Sync.ProdutosImpostosReference.priaExcluirImpostoRequest priaExcluirImpostoRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLListarImpostos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(listaImpostos))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaListResponse")]
        Sync.ProdutosImpostosReference.priaListResponse ListarImpostos(Sync.ProdutosImpostosReference.priaListRequest priaListRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/prodimp/?WSDLListarImpostos", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="priaListResponse")]
        System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaListResponse> ListarImpostosAsync(Sync.ProdutosImpostosReference.priaListRequest priaListRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaIncluirImpostoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ident identField;
        
        private cabec cabecField;
        
        private ECF eCFField;
        
        private ICMS iCMSField;
        
        private ICMSSN iCMSSNField;
        
        private ICMSST iCMSSTField;
        
        private ICMSIE iCMSIEField;
        
        private PIS pISField;
        
        private COFINS cOFINSField;
        
        private IPI iPIField;
        
        private InfAdic infAdicField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ident ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
                this.RaisePropertyChanged("ident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cabec cabec {
            get {
                return this.cabecField;
            }
            set {
                this.cabecField = value;
                this.RaisePropertyChanged("cabec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ECF ECF {
            get {
                return this.eCFField;
            }
            set {
                this.eCFField = value;
                this.RaisePropertyChanged("ECF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMS ICMS {
            get {
                return this.iCMSField;
            }
            set {
                this.iCMSField = value;
                this.RaisePropertyChanged("ICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSSN ICMSSN {
            get {
                return this.iCMSSNField;
            }
            set {
                this.iCMSSNField = value;
                this.RaisePropertyChanged("ICMSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSST ICMSST {
            get {
                return this.iCMSSTField;
            }
            set {
                this.iCMSSTField = value;
                this.RaisePropertyChanged("ICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSIE ICMSIE {
            get {
                return this.iCMSIEField;
            }
            set {
                this.iCMSIEField = value;
                this.RaisePropertyChanged("ICMSIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PIS PIS {
            get {
                return this.pISField;
            }
            set {
                this.pISField = value;
                this.RaisePropertyChanged("PIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public COFINS COFINS {
            get {
                return this.cOFINSField;
            }
            set {
                this.cOFINSField = value;
                this.RaisePropertyChanged("COFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public IPI IPI {
            get {
                return this.iPIField;
            }
            set {
                this.iPIField = value;
                this.RaisePropertyChanged("IPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InfAdic InfAdic {
            get {
                return this.infAdicField;
            }
            set {
                this.infAdicField = value;
                this.RaisePropertyChanged("InfAdic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ident : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class listaImpostos : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ident identField;
        
        private cabec cabecField;
        
        private ECF eCFField;
        
        private ICMS iCMSField;
        
        private ICMSSN iCMSSNField;
        
        private ICMSST iCMSSTField;
        
        private ICMSIE iCMSIEField;
        
        private PIS pISField;
        
        private COFINS cOFINSField;
        
        private IPI iPIField;
        
        private InfAdic infAdicField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ident ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
                this.RaisePropertyChanged("ident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cabec cabec {
            get {
                return this.cabecField;
            }
            set {
                this.cabecField = value;
                this.RaisePropertyChanged("cabec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ECF ECF {
            get {
                return this.eCFField;
            }
            set {
                this.eCFField = value;
                this.RaisePropertyChanged("ECF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMS ICMS {
            get {
                return this.iCMSField;
            }
            set {
                this.iCMSField = value;
                this.RaisePropertyChanged("ICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSSN ICMSSN {
            get {
                return this.iCMSSNField;
            }
            set {
                this.iCMSSNField = value;
                this.RaisePropertyChanged("ICMSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSST ICMSST {
            get {
                return this.iCMSSTField;
            }
            set {
                this.iCMSSTField = value;
                this.RaisePropertyChanged("ICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSIE ICMSIE {
            get {
                return this.iCMSIEField;
            }
            set {
                this.iCMSIEField = value;
                this.RaisePropertyChanged("ICMSIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PIS PIS {
            get {
                return this.pISField;
            }
            set {
                this.pISField = value;
                this.RaisePropertyChanged("PIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public COFINS COFINS {
            get {
                return this.cOFINSField;
            }
            set {
                this.cOFINSField = value;
                this.RaisePropertyChanged("COFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public IPI IPI {
            get {
                return this.iPIField;
            }
            set {
                this.iPIField = value;
                this.RaisePropertyChanged("IPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InfAdic InfAdic {
            get {
                return this.infAdicField;
            }
            set {
                this.infAdicField = value;
                this.RaisePropertyChanged("InfAdic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class cabec : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCupomFiscalField;
        
        private string cUfOrigemField;
        
        private string cUfDestinoField;
        
        private string cCFOPField;
        
        private string cCNAEClienteField;
        
        private string cContribICMSField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCupomFiscal {
            get {
                return this.cCupomFiscalField;
            }
            set {
                this.cCupomFiscalField = value;
                this.RaisePropertyChanged("cCupomFiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cUfOrigem {
            get {
                return this.cUfOrigemField;
            }
            set {
                this.cUfOrigemField = value;
                this.RaisePropertyChanged("cUfOrigem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cUfDestino {
            get {
                return this.cUfDestinoField;
            }
            set {
                this.cUfDestinoField = value;
                this.RaisePropertyChanged("cUfDestino");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCFOP {
            get {
                return this.cCFOPField;
            }
            set {
                this.cCFOPField = value;
                this.RaisePropertyChanged("cCFOP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCNAECliente {
            get {
                return this.cCNAEClienteField;
            }
            set {
                this.cCNAEClienteField = value;
                this.RaisePropertyChanged("cCNAECliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cContribICMS {
            get {
                return this.cContribICMSField;
            }
            set {
                this.cContribICMSField = value;
                this.RaisePropertyChanged("cContribICMS");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ECF : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cECFNaoTribField;
        
        private string cECFSubstTribField;
        
        private string cECFIsentoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cECFNaoTrib {
            get {
                return this.cECFNaoTribField;
            }
            set {
                this.cECFNaoTribField = value;
                this.RaisePropertyChanged("cECFNaoTrib");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cECFSubstTrib {
            get {
                return this.cECFSubstTribField;
            }
            set {
                this.cECFSubstTribField = value;
                this.RaisePropertyChanged("cECFSubstTrib");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cECFIsento {
            get {
                return this.cECFIsentoField;
            }
            set {
                this.cECFIsentoField = value;
                this.RaisePropertyChanged("cECFIsento");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ICMS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCSTICMSField;
        
        private string cOrigemICMSField;
        
        private string cModBCICMSField;
        
        private System.Nullable<decimal> nRedBCICMSField;
        
        private bool nRedBCICMSFieldSpecified;
        
        private System.Nullable<decimal> nAliqICMSField;
        
        private bool nAliqICMSFieldSpecified;
        
        private System.Nullable<decimal> nPercDifICMSField;
        
        private bool nPercDifICMSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCSTICMS {
            get {
                return this.cCSTICMSField;
            }
            set {
                this.cCSTICMSField = value;
                this.RaisePropertyChanged("cCSTICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cOrigemICMS {
            get {
                return this.cOrigemICMSField;
            }
            set {
                this.cOrigemICMSField = value;
                this.RaisePropertyChanged("cOrigemICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cModBCICMS {
            get {
                return this.cModBCICMSField;
            }
            set {
                this.cModBCICMSField = value;
                this.RaisePropertyChanged("cModBCICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nRedBCICMS {
            get {
                return this.nRedBCICMSField;
            }
            set {
                this.nRedBCICMSField = value;
                this.RaisePropertyChanged("nRedBCICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nRedBCICMSSpecified {
            get {
                return this.nRedBCICMSFieldSpecified;
            }
            set {
                this.nRedBCICMSFieldSpecified = value;
                this.RaisePropertyChanged("nRedBCICMSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqICMS {
            get {
                return this.nAliqICMSField;
            }
            set {
                this.nAliqICMSField = value;
                this.RaisePropertyChanged("nAliqICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqICMSSpecified {
            get {
                return this.nAliqICMSFieldSpecified;
            }
            set {
                this.nAliqICMSFieldSpecified = value;
                this.RaisePropertyChanged("nAliqICMSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nPercDifICMS {
            get {
                return this.nPercDifICMSField;
            }
            set {
                this.nPercDifICMSField = value;
                this.RaisePropertyChanged("nPercDifICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nPercDifICMSSpecified {
            get {
                return this.nPercDifICMSFieldSpecified;
            }
            set {
                this.nPercDifICMSFieldSpecified = value;
                this.RaisePropertyChanged("nPercDifICMSSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ICMSSN : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCSOSNICMSField;
        
        private string cOrigemICMSField;
        
        private string cModBCICMSField;
        
        private System.Nullable<decimal> nAlCredICMSField;
        
        private bool nAlCredICMSFieldSpecified;
        
        private System.Nullable<decimal> nRedBCICMSField;
        
        private bool nRedBCICMSFieldSpecified;
        
        private System.Nullable<decimal> nAliqICMSField;
        
        private bool nAliqICMSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCSOSNICMS {
            get {
                return this.cCSOSNICMSField;
            }
            set {
                this.cCSOSNICMSField = value;
                this.RaisePropertyChanged("cCSOSNICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cOrigemICMS {
            get {
                return this.cOrigemICMSField;
            }
            set {
                this.cOrigemICMSField = value;
                this.RaisePropertyChanged("cOrigemICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cModBCICMS {
            get {
                return this.cModBCICMSField;
            }
            set {
                this.cModBCICMSField = value;
                this.RaisePropertyChanged("cModBCICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAlCredICMS {
            get {
                return this.nAlCredICMSField;
            }
            set {
                this.nAlCredICMSField = value;
                this.RaisePropertyChanged("nAlCredICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAlCredICMSSpecified {
            get {
                return this.nAlCredICMSFieldSpecified;
            }
            set {
                this.nAlCredICMSFieldSpecified = value;
                this.RaisePropertyChanged("nAlCredICMSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nRedBCICMS {
            get {
                return this.nRedBCICMSField;
            }
            set {
                this.nRedBCICMSField = value;
                this.RaisePropertyChanged("nRedBCICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nRedBCICMSSpecified {
            get {
                return this.nRedBCICMSFieldSpecified;
            }
            set {
                this.nRedBCICMSFieldSpecified = value;
                this.RaisePropertyChanged("nRedBCICMSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqICMS {
            get {
                return this.nAliqICMSField;
            }
            set {
                this.nAliqICMSField = value;
                this.RaisePropertyChanged("nAliqICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqICMSSpecified {
            get {
                return this.nAliqICMSFieldSpecified;
            }
            set {
                this.nAliqICMSFieldSpecified = value;
                this.RaisePropertyChanged("nAliqICMSSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ICMSST : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cModBCICMSSTField;
        
        private System.Nullable<decimal> nMargValAdICMSSTField;
        
        private bool nMargValAdICMSSTFieldSpecified;
        
        private System.Nullable<decimal> nRedBCICMSSTField;
        
        private bool nRedBCICMSSTFieldSpecified;
        
        private System.Nullable<decimal> nAliqICMSSTField;
        
        private bool nAliqICMSSTFieldSpecified;
        
        private System.Nullable<decimal> nAliqOPICMSSTField;
        
        private bool nAliqOPICMSSTFieldSpecified;
        
        private string cCESTField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cModBCICMSST {
            get {
                return this.cModBCICMSSTField;
            }
            set {
                this.cModBCICMSSTField = value;
                this.RaisePropertyChanged("cModBCICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nMargValAdICMSST {
            get {
                return this.nMargValAdICMSSTField;
            }
            set {
                this.nMargValAdICMSSTField = value;
                this.RaisePropertyChanged("nMargValAdICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nMargValAdICMSSTSpecified {
            get {
                return this.nMargValAdICMSSTFieldSpecified;
            }
            set {
                this.nMargValAdICMSSTFieldSpecified = value;
                this.RaisePropertyChanged("nMargValAdICMSSTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nRedBCICMSST {
            get {
                return this.nRedBCICMSSTField;
            }
            set {
                this.nRedBCICMSSTField = value;
                this.RaisePropertyChanged("nRedBCICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nRedBCICMSSTSpecified {
            get {
                return this.nRedBCICMSSTFieldSpecified;
            }
            set {
                this.nRedBCICMSSTFieldSpecified = value;
                this.RaisePropertyChanged("nRedBCICMSSTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqICMSST {
            get {
                return this.nAliqICMSSTField;
            }
            set {
                this.nAliqICMSSTField = value;
                this.RaisePropertyChanged("nAliqICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqICMSSTSpecified {
            get {
                return this.nAliqICMSSTFieldSpecified;
            }
            set {
                this.nAliqICMSSTFieldSpecified = value;
                this.RaisePropertyChanged("nAliqICMSSTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqOPICMSST {
            get {
                return this.nAliqOPICMSSTField;
            }
            set {
                this.nAliqOPICMSSTField = value;
                this.RaisePropertyChanged("nAliqOPICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqOPICMSSTSpecified {
            get {
                return this.nAliqOPICMSSTFieldSpecified;
            }
            set {
                this.nAliqOPICMSSTFieldSpecified = value;
                this.RaisePropertyChanged("nAliqOPICMSSTSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCEST {
            get {
                return this.cCESTField;
            }
            set {
                this.cCESTField = value;
                this.RaisePropertyChanged("cCEST");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class ICMSIE : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> nPercFCPField;
        
        private bool nPercFCPFieldSpecified;
        
        private System.Nullable<decimal> nAlIntUFDestField;
        
        private bool nAlIntUFDestFieldSpecified;
        
        private System.Nullable<decimal> nAlInterestUFsField;
        
        private bool nAlInterestUFsFieldSpecified;
        
        private System.Nullable<decimal> nPercICMSIEField;
        
        private bool nPercICMSIEFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nPercFCP {
            get {
                return this.nPercFCPField;
            }
            set {
                this.nPercFCPField = value;
                this.RaisePropertyChanged("nPercFCP");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nPercFCPSpecified {
            get {
                return this.nPercFCPFieldSpecified;
            }
            set {
                this.nPercFCPFieldSpecified = value;
                this.RaisePropertyChanged("nPercFCPSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAlIntUFDest {
            get {
                return this.nAlIntUFDestField;
            }
            set {
                this.nAlIntUFDestField = value;
                this.RaisePropertyChanged("nAlIntUFDest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAlIntUFDestSpecified {
            get {
                return this.nAlIntUFDestFieldSpecified;
            }
            set {
                this.nAlIntUFDestFieldSpecified = value;
                this.RaisePropertyChanged("nAlIntUFDestSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAlInterestUFs {
            get {
                return this.nAlInterestUFsField;
            }
            set {
                this.nAlInterestUFsField = value;
                this.RaisePropertyChanged("nAlInterestUFs");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAlInterestUFsSpecified {
            get {
                return this.nAlInterestUFsFieldSpecified;
            }
            set {
                this.nAlInterestUFsFieldSpecified = value;
                this.RaisePropertyChanged("nAlInterestUFsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nPercICMSIE {
            get {
                return this.nPercICMSIEField;
            }
            set {
                this.nPercICMSIEField = value;
                this.RaisePropertyChanged("nPercICMSIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nPercICMSIESpecified {
            get {
                return this.nPercICMSIEFieldSpecified;
            }
            set {
                this.nPercICMSIEFieldSpecified = value;
                this.RaisePropertyChanged("nPercICMSIESpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class PIS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCSTPISField;
        
        private string cTpCalcPISField;
        
        private System.Nullable<decimal> nAliqPISField;
        
        private bool nAliqPISFieldSpecified;
        
        private System.Nullable<decimal> nValUnTribPISField;
        
        private bool nValUnTribPISFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCSTPIS {
            get {
                return this.cCSTPISField;
            }
            set {
                this.cCSTPISField = value;
                this.RaisePropertyChanged("cCSTPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cTpCalcPIS {
            get {
                return this.cTpCalcPISField;
            }
            set {
                this.cTpCalcPISField = value;
                this.RaisePropertyChanged("cTpCalcPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqPIS {
            get {
                return this.nAliqPISField;
            }
            set {
                this.nAliqPISField = value;
                this.RaisePropertyChanged("nAliqPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqPISSpecified {
            get {
                return this.nAliqPISFieldSpecified;
            }
            set {
                this.nAliqPISFieldSpecified = value;
                this.RaisePropertyChanged("nAliqPISSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nValUnTribPIS {
            get {
                return this.nValUnTribPISField;
            }
            set {
                this.nValUnTribPISField = value;
                this.RaisePropertyChanged("nValUnTribPIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nValUnTribPISSpecified {
            get {
                return this.nValUnTribPISFieldSpecified;
            }
            set {
                this.nValUnTribPISFieldSpecified = value;
                this.RaisePropertyChanged("nValUnTribPISSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class COFINS : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCSTCOFINSField;
        
        private string cTpCalcCOFINSField;
        
        private System.Nullable<decimal> nAliqCOFINSField;
        
        private bool nAliqCOFINSFieldSpecified;
        
        private System.Nullable<decimal> nValUnTribCOFINSField;
        
        private bool nValUnTribCOFINSFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCSTCOFINS {
            get {
                return this.cCSTCOFINSField;
            }
            set {
                this.cCSTCOFINSField = value;
                this.RaisePropertyChanged("cCSTCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cTpCalcCOFINS {
            get {
                return this.cTpCalcCOFINSField;
            }
            set {
                this.cTpCalcCOFINSField = value;
                this.RaisePropertyChanged("cTpCalcCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqCOFINS {
            get {
                return this.nAliqCOFINSField;
            }
            set {
                this.nAliqCOFINSField = value;
                this.RaisePropertyChanged("nAliqCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqCOFINSSpecified {
            get {
                return this.nAliqCOFINSFieldSpecified;
            }
            set {
                this.nAliqCOFINSFieldSpecified = value;
                this.RaisePropertyChanged("nAliqCOFINSSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nValUnTribCOFINS {
            get {
                return this.nValUnTribCOFINSField;
            }
            set {
                this.nValUnTribCOFINSField = value;
                this.RaisePropertyChanged("nValUnTribCOFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nValUnTribCOFINSSpecified {
            get {
                return this.nValUnTribCOFINSFieldSpecified;
            }
            set {
                this.nValUnTribCOFINSFieldSpecified = value;
                this.RaisePropertyChanged("nValUnTribCOFINSSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class IPI : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCSTIPIField;
        
        private string cTpCalcIPIField;
        
        private System.Nullable<decimal> nAliqIPIField;
        
        private bool nAliqIPIFieldSpecified;
        
        private System.Nullable<decimal> nValUnTribIPIField;
        
        private bool nValUnTribIPIFieldSpecified;
        
        private string cEnqIPIField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCSTIPI {
            get {
                return this.cCSTIPIField;
            }
            set {
                this.cCSTIPIField = value;
                this.RaisePropertyChanged("cCSTIPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cTpCalcIPI {
            get {
                return this.cTpCalcIPIField;
            }
            set {
                this.cTpCalcIPIField = value;
                this.RaisePropertyChanged("cTpCalcIPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nAliqIPI {
            get {
                return this.nAliqIPIField;
            }
            set {
                this.nAliqIPIField = value;
                this.RaisePropertyChanged("nAliqIPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nAliqIPISpecified {
            get {
                return this.nAliqIPIFieldSpecified;
            }
            set {
                this.nAliqIPIFieldSpecified = value;
                this.RaisePropertyChanged("nAliqIPISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nValUnTribIPI {
            get {
                return this.nValUnTribIPIField;
            }
            set {
                this.nValUnTribIPIField = value;
                this.RaisePropertyChanged("nValUnTribIPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nValUnTribIPISpecified {
            get {
                return this.nValUnTribIPIFieldSpecified;
            }
            set {
                this.nValUnTribIPIFieldSpecified = value;
                this.RaisePropertyChanged("nValUnTribIPISpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cEnqIPI {
            get {
                return this.cEnqIPIField;
            }
            set {
                this.cEnqIPIField = value;
                this.RaisePropertyChanged("cEnqIPI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class InfAdic : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cInfAdicNFField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cInfAdicNF {
            get {
                return this.cInfAdicNFField;
            }
            set {
                this.cInfAdicNFField = value;
                this.RaisePropertyChanged("cInfAdicNF");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaListResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private listaImpostos[] listaImpostosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public listaImpostos[] listaImpostos {
            get {
                return this.listaImpostosField;
            }
            set {
                this.listaImpostosField = value;
                this.RaisePropertyChanged("listaImpostos");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaListRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        private string filtrar_apenas_cupomfiscalField;
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_cupomfiscal {
            get {
                return this.filtrar_apenas_cupomfiscalField;
            }
            set {
                this.filtrar_apenas_cupomfiscalField = value;
                this.RaisePropertyChanged("filtrar_apenas_cupomfiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaExcluirImpostoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        private string cCodStatusField;
        
        private string cDescStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDescStatus {
            get {
                return this.cDescStatusField;
            }
            set {
                this.cDescStatusField = value;
                this.RaisePropertyChanged("cDescStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaExcluirImpostoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaUpsertImpostoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        private string cCodStatusField;
        
        private string cDescStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDescStatus {
            get {
                return this.cDescStatusField;
            }
            set {
                this.cDescStatusField = value;
                this.RaisePropertyChanged("cDescStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaUpsertImpostoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ident identField;
        
        private cabec cabecField;
        
        private ECF eCFField;
        
        private ICMS iCMSField;
        
        private ICMSSN iCMSSNField;
        
        private ICMSST iCMSSTField;
        
        private ICMSIE iCMSIEField;
        
        private PIS pISField;
        
        private COFINS cOFINSField;
        
        private IPI iPIField;
        
        private InfAdic infAdicField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ident ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
                this.RaisePropertyChanged("ident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cabec cabec {
            get {
                return this.cabecField;
            }
            set {
                this.cabecField = value;
                this.RaisePropertyChanged("cabec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ECF ECF {
            get {
                return this.eCFField;
            }
            set {
                this.eCFField = value;
                this.RaisePropertyChanged("ECF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMS ICMS {
            get {
                return this.iCMSField;
            }
            set {
                this.iCMSField = value;
                this.RaisePropertyChanged("ICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSSN ICMSSN {
            get {
                return this.iCMSSNField;
            }
            set {
                this.iCMSSNField = value;
                this.RaisePropertyChanged("ICMSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSST ICMSST {
            get {
                return this.iCMSSTField;
            }
            set {
                this.iCMSSTField = value;
                this.RaisePropertyChanged("ICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSIE ICMSIE {
            get {
                return this.iCMSIEField;
            }
            set {
                this.iCMSIEField = value;
                this.RaisePropertyChanged("ICMSIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PIS PIS {
            get {
                return this.pISField;
            }
            set {
                this.pISField = value;
                this.RaisePropertyChanged("PIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public COFINS COFINS {
            get {
                return this.cOFINSField;
            }
            set {
                this.cOFINSField = value;
                this.RaisePropertyChanged("COFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public IPI IPI {
            get {
                return this.iPIField;
            }
            set {
                this.iPIField = value;
                this.RaisePropertyChanged("IPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InfAdic InfAdic {
            get {
                return this.infAdicField;
            }
            set {
                this.infAdicField = value;
                this.RaisePropertyChanged("InfAdic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaAlterarImpostoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        private string cCodStatusField;
        
        private string cDescStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDescStatus {
            get {
                return this.cDescStatusField;
            }
            set {
                this.cDescStatusField = value;
                this.RaisePropertyChanged("cDescStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaAlterarImpostoRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ident identField;
        
        private cabec cabecField;
        
        private ECF eCFField;
        
        private ICMS iCMSField;
        
        private ICMSSN iCMSSNField;
        
        private ICMSST iCMSSTField;
        
        private ICMSIE iCMSIEField;
        
        private PIS pISField;
        
        private COFINS cOFINSField;
        
        private IPI iPIField;
        
        private InfAdic infAdicField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ident ident {
            get {
                return this.identField;
            }
            set {
                this.identField = value;
                this.RaisePropertyChanged("ident");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cabec cabec {
            get {
                return this.cabecField;
            }
            set {
                this.cabecField = value;
                this.RaisePropertyChanged("cabec");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ECF ECF {
            get {
                return this.eCFField;
            }
            set {
                this.eCFField = value;
                this.RaisePropertyChanged("ECF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMS ICMS {
            get {
                return this.iCMSField;
            }
            set {
                this.iCMSField = value;
                this.RaisePropertyChanged("ICMS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSSN ICMSSN {
            get {
                return this.iCMSSNField;
            }
            set {
                this.iCMSSNField = value;
                this.RaisePropertyChanged("ICMSSN");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSST ICMSST {
            get {
                return this.iCMSSTField;
            }
            set {
                this.iCMSSTField = value;
                this.RaisePropertyChanged("ICMSST");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public ICMSIE ICMSIE {
            get {
                return this.iCMSIEField;
            }
            set {
                this.iCMSIEField = value;
                this.RaisePropertyChanged("ICMSIE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public PIS PIS {
            get {
                return this.pISField;
            }
            set {
                this.pISField = value;
                this.RaisePropertyChanged("PIS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public COFINS COFINS {
            get {
                return this.cOFINSField;
            }
            set {
                this.cOFINSField = value;
                this.RaisePropertyChanged("COFINS");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public IPI IPI {
            get {
                return this.iPIField;
            }
            set {
                this.iPIField = value;
                this.RaisePropertyChanged("IPI");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public InfAdic InfAdic {
            get {
                return this.infAdicField;
            }
            set {
                this.infAdicField = value;
                this.RaisePropertyChanged("InfAdic");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/prodimp/?WSDL")]
    public partial class priaIncluirImpostoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodProdField;
        
        private string cCodIntProdField;
        
        private string cCodIntImpField;
        
        private string cCodStatusField;
        
        private string cDescStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodProd {
            get {
                return this.nCodProdField;
            }
            set {
                this.nCodProdField = value;
                this.RaisePropertyChanged("nCodProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntProd {
            get {
                return this.cCodIntProdField;
            }
            set {
                this.cCodIntProdField = value;
                this.RaisePropertyChanged("cCodIntProd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodIntImp {
            get {
                return this.cCodIntImpField;
            }
            set {
                this.cCodIntImpField = value;
                this.RaisePropertyChanged("cCodIntImp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDescStatus {
            get {
                return this.cDescStatusField;
            }
            set {
                this.cDescStatusField = value;
                this.RaisePropertyChanged("cDescStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdutosImpostosSoapChannel : Sync.ProdutosImpostosReference.ProdutosImpostosSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosImpostosSoapClient : System.ServiceModel.ClientBase<Sync.ProdutosImpostosReference.ProdutosImpostosSoap>, Sync.ProdutosImpostosReference.ProdutosImpostosSoap {
        
        public ProdutosImpostosSoapClient() {
        }
        
        public ProdutosImpostosSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosImpostosSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosImpostosSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosImpostosSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.ProdutosImpostosReference.priaIncluirImpostoResponse IncluirImposto(Sync.ProdutosImpostosReference.priaIncluirImpostoRequest priaIncluirImpostoRequest) {
            return base.Channel.IncluirImposto(priaIncluirImpostoRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaIncluirImpostoResponse> IncluirImpostoAsync(Sync.ProdutosImpostosReference.priaIncluirImpostoRequest priaIncluirImpostoRequest) {
            return base.Channel.IncluirImpostoAsync(priaIncluirImpostoRequest);
        }
        
        public Sync.ProdutosImpostosReference.priaAlterarImpostoResponse AlterarImposto(Sync.ProdutosImpostosReference.priaAlterarImpostoRequest priaAlterarImpostoRequest) {
            return base.Channel.AlterarImposto(priaAlterarImpostoRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaAlterarImpostoResponse> AlterarImpostoAsync(Sync.ProdutosImpostosReference.priaAlterarImpostoRequest priaAlterarImpostoRequest) {
            return base.Channel.AlterarImpostoAsync(priaAlterarImpostoRequest);
        }
        
        public Sync.ProdutosImpostosReference.priaUpsertImpostoResponse UpsertImposto(Sync.ProdutosImpostosReference.priaUpsertImpostoRequest priaUpsertImpostoRequest) {
            return base.Channel.UpsertImposto(priaUpsertImpostoRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaUpsertImpostoResponse> UpsertImpostoAsync(Sync.ProdutosImpostosReference.priaUpsertImpostoRequest priaUpsertImpostoRequest) {
            return base.Channel.UpsertImpostoAsync(priaUpsertImpostoRequest);
        }
        
        public Sync.ProdutosImpostosReference.priaExcluirImpostoResponse ExcluirImposto(Sync.ProdutosImpostosReference.priaExcluirImpostoRequest priaExcluirImpostoRequest) {
            return base.Channel.ExcluirImposto(priaExcluirImpostoRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaExcluirImpostoResponse> ExcluirImpostoAsync(Sync.ProdutosImpostosReference.priaExcluirImpostoRequest priaExcluirImpostoRequest) {
            return base.Channel.ExcluirImpostoAsync(priaExcluirImpostoRequest);
        }
        
        public Sync.ProdutosImpostosReference.priaListResponse ListarImpostos(Sync.ProdutosImpostosReference.priaListRequest priaListRequest) {
            return base.Channel.ListarImpostos(priaListRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.ProdutosImpostosReference.priaListResponse> ListarImpostosAsync(Sync.ProdutosImpostosReference.priaListRequest priaListRequest) {
            return base.Channel.ListarImpostosAsync(priaListRequest);
        }
    }
}
