//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.ContaCorrenteCadastroReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL", ConfigurationName="ContaCorrenteCadastroReference.ContaCorrenteCadastroSoap")]
    public interface ContaCorrenteCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLIncluirContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response IncluirContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLIncluirContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> IncluirContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLAlterarContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response AlterarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLAlterarContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> AlterarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLExcluirContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response ExcluirContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLExcluirContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> ExcluirContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLConsultarContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro ConsultarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLConsultarContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro> ConsultarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLPesquisarContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_pesquisar_resposta")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar_resposta PesquisarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar fin_conta_corrente_pesquisar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLPesquisarContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_pesquisar_resposta")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar_resposta> PesquisarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar fin_conta_corrente_pesquisar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLUpsertContaCorrente", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response UpsertContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLUpsertContaCorrente", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_cadastro_response")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> UpsertContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLUpsertContaCorrentePorLote" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(conta_corrente_lista))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_lote_response")]
        Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_response UpsertContaCorrentePorLote(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_request fin_conta_corrente_lote_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDLUpsertContaCorrentePorLote" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="fin_conta_corrente_lote_response")]
        System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_response> UpsertContaCorrentePorLoteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_request fin_conta_corrente_lote_request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_cadastro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodCCField;
        
        private string cCodCCIntField;
        
        private string tipo_conta_correnteField;
        
        private string codigo_bancoField;
        
        private string descricaoField;
        
        private string codigo_agenciaField;
        
        private string numero_conta_correnteField;
        
        private System.Nullable<decimal> saldo_inicialField;
        
        private bool saldo_inicialFieldSpecified;
        
        private string saldo_dataField;
        
        private System.Nullable<decimal> valor_limiteField;
        
        private bool valor_limiteFieldSpecified;
        
        private string nao_fluxoField;
        
        private string nao_resumoField;
        
        private string observacaoField;
        
        private string cobr_snField;
        
        private System.Nullable<decimal> per_jurosField;
        
        private bool per_jurosFieldSpecified;
        
        private System.Nullable<decimal> per_multaField;
        
        private bool per_multaFieldSpecified;
        
        private string bol_instr1Field;
        
        private string bol_instr2Field;
        
        private string bol_instr3Field;
        
        private string bol_instr4Field;
        
        private string bol_snField;
        
        private string cnab_espField;
        
        private string cobr_espField;
        
        private string dias_rcompField;
        
        private string modalidadeField;
        
        private string cancinstrField;
        
        private string pdv_enviarField;
        
        private string pdv_sincr_analiticaField;
        
        private string pdv_dias_vencField;
        
        private string pdv_num_parcelasField;
        
        private string pdv_tipo_tefField;
        
        private string pdv_cod_admField;
        
        private string pdv_limite_pacelasField;
        
        private System.Nullable<decimal> pdv_taxa_lojaField;
        
        private bool pdv_taxa_lojaFieldSpecified;
        
        private System.Nullable<decimal> pdv_taxa_admField;
        
        private bool pdv_taxa_admFieldSpecified;
        
        private string nome_gerenteField;
        
        private string dddField;
        
        private string telefoneField;
        
        private string emailField;
        
        private string enderecoField;
        
        private string numeroField;
        
        private string bairroField;
        
        private string complementoField;
        
        private string estadoField;
        
        private string cidadeField;
        
        private string cepField;
        
        private string codigo_paisField;
        
        private string data_incField;
        
        private string hora_incField;
        
        private string user_incField;
        
        private string data_altField;
        
        private string hora_altField;
        
        private string user_altField;
        
        private string importado_apiField;
        
        private string bloqueadoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodCC {
            get {
                return this.nCodCCField;
            }
            set {
                this.nCodCCField = value;
                this.RaisePropertyChanged("nCodCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodCCInt {
            get {
                return this.cCodCCIntField;
            }
            set {
                this.cCodCCIntField = value;
                this.RaisePropertyChanged("cCodCCInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo_conta_corrente {
            get {
                return this.tipo_conta_correnteField;
            }
            set {
                this.tipo_conta_correnteField = value;
                this.RaisePropertyChanged("tipo_conta_corrente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_banco {
            get {
                return this.codigo_bancoField;
            }
            set {
                this.codigo_bancoField = value;
                this.RaisePropertyChanged("codigo_banco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_agencia {
            get {
                return this.codigo_agenciaField;
            }
            set {
                this.codigo_agenciaField = value;
                this.RaisePropertyChanged("codigo_agencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numero_conta_corrente {
            get {
                return this.numero_conta_correnteField;
            }
            set {
                this.numero_conta_correnteField = value;
                this.RaisePropertyChanged("numero_conta_corrente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> saldo_inicial {
            get {
                return this.saldo_inicialField;
            }
            set {
                this.saldo_inicialField = value;
                this.RaisePropertyChanged("saldo_inicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool saldo_inicialSpecified {
            get {
                return this.saldo_inicialFieldSpecified;
            }
            set {
                this.saldo_inicialFieldSpecified = value;
                this.RaisePropertyChanged("saldo_inicialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string saldo_data {
            get {
                return this.saldo_dataField;
            }
            set {
                this.saldo_dataField = value;
                this.RaisePropertyChanged("saldo_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor_limite {
            get {
                return this.valor_limiteField;
            }
            set {
                this.valor_limiteField = value;
                this.RaisePropertyChanged("valor_limite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valor_limiteSpecified {
            get {
                return this.valor_limiteFieldSpecified;
            }
            set {
                this.valor_limiteFieldSpecified = value;
                this.RaisePropertyChanged("valor_limiteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nao_fluxo {
            get {
                return this.nao_fluxoField;
            }
            set {
                this.nao_fluxoField = value;
                this.RaisePropertyChanged("nao_fluxo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nao_resumo {
            get {
                return this.nao_resumoField;
            }
            set {
                this.nao_resumoField = value;
                this.RaisePropertyChanged("nao_resumo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string observacao {
            get {
                return this.observacaoField;
            }
            set {
                this.observacaoField = value;
                this.RaisePropertyChanged("observacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cobr_sn {
            get {
                return this.cobr_snField;
            }
            set {
                this.cobr_snField = value;
                this.RaisePropertyChanged("cobr_sn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> per_juros {
            get {
                return this.per_jurosField;
            }
            set {
                this.per_jurosField = value;
                this.RaisePropertyChanged("per_juros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool per_jurosSpecified {
            get {
                return this.per_jurosFieldSpecified;
            }
            set {
                this.per_jurosFieldSpecified = value;
                this.RaisePropertyChanged("per_jurosSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> per_multa {
            get {
                return this.per_multaField;
            }
            set {
                this.per_multaField = value;
                this.RaisePropertyChanged("per_multa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool per_multaSpecified {
            get {
                return this.per_multaFieldSpecified;
            }
            set {
                this.per_multaFieldSpecified = value;
                this.RaisePropertyChanged("per_multaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bol_instr1 {
            get {
                return this.bol_instr1Field;
            }
            set {
                this.bol_instr1Field = value;
                this.RaisePropertyChanged("bol_instr1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bol_instr2 {
            get {
                return this.bol_instr2Field;
            }
            set {
                this.bol_instr2Field = value;
                this.RaisePropertyChanged("bol_instr2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bol_instr3 {
            get {
                return this.bol_instr3Field;
            }
            set {
                this.bol_instr3Field = value;
                this.RaisePropertyChanged("bol_instr3");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bol_instr4 {
            get {
                return this.bol_instr4Field;
            }
            set {
                this.bol_instr4Field = value;
                this.RaisePropertyChanged("bol_instr4");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bol_sn {
            get {
                return this.bol_snField;
            }
            set {
                this.bol_snField = value;
                this.RaisePropertyChanged("bol_sn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnab_esp {
            get {
                return this.cnab_espField;
            }
            set {
                this.cnab_espField = value;
                this.RaisePropertyChanged("cnab_esp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cobr_esp {
            get {
                return this.cobr_espField;
            }
            set {
                this.cobr_espField = value;
                this.RaisePropertyChanged("cobr_esp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string dias_rcomp {
            get {
                return this.dias_rcompField;
            }
            set {
                this.dias_rcompField = value;
                this.RaisePropertyChanged("dias_rcomp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string modalidade {
            get {
                return this.modalidadeField;
            }
            set {
                this.modalidadeField = value;
                this.RaisePropertyChanged("modalidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cancinstr {
            get {
                return this.cancinstrField;
            }
            set {
                this.cancinstrField = value;
                this.RaisePropertyChanged("cancinstr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pdv_enviar {
            get {
                return this.pdv_enviarField;
            }
            set {
                this.pdv_enviarField = value;
                this.RaisePropertyChanged("pdv_enviar");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pdv_sincr_analitica {
            get {
                return this.pdv_sincr_analiticaField;
            }
            set {
                this.pdv_sincr_analiticaField = value;
                this.RaisePropertyChanged("pdv_sincr_analitica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pdv_dias_venc {
            get {
                return this.pdv_dias_vencField;
            }
            set {
                this.pdv_dias_vencField = value;
                this.RaisePropertyChanged("pdv_dias_venc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pdv_num_parcelas {
            get {
                return this.pdv_num_parcelasField;
            }
            set {
                this.pdv_num_parcelasField = value;
                this.RaisePropertyChanged("pdv_num_parcelas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pdv_tipo_tef {
            get {
                return this.pdv_tipo_tefField;
            }
            set {
                this.pdv_tipo_tefField = value;
                this.RaisePropertyChanged("pdv_tipo_tef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pdv_cod_adm {
            get {
                return this.pdv_cod_admField;
            }
            set {
                this.pdv_cod_admField = value;
                this.RaisePropertyChanged("pdv_cod_adm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pdv_limite_pacelas {
            get {
                return this.pdv_limite_pacelasField;
            }
            set {
                this.pdv_limite_pacelasField = value;
                this.RaisePropertyChanged("pdv_limite_pacelas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pdv_taxa_loja {
            get {
                return this.pdv_taxa_lojaField;
            }
            set {
                this.pdv_taxa_lojaField = value;
                this.RaisePropertyChanged("pdv_taxa_loja");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool pdv_taxa_lojaSpecified {
            get {
                return this.pdv_taxa_lojaFieldSpecified;
            }
            set {
                this.pdv_taxa_lojaFieldSpecified = value;
                this.RaisePropertyChanged("pdv_taxa_lojaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> pdv_taxa_adm {
            get {
                return this.pdv_taxa_admField;
            }
            set {
                this.pdv_taxa_admField = value;
                this.RaisePropertyChanged("pdv_taxa_adm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool pdv_taxa_admSpecified {
            get {
                return this.pdv_taxa_admFieldSpecified;
            }
            set {
                this.pdv_taxa_admFieldSpecified = value;
                this.RaisePropertyChanged("pdv_taxa_admSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_gerente {
            get {
                return this.nome_gerenteField;
            }
            set {
                this.nome_gerenteField = value;
                this.RaisePropertyChanged("nome_gerente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ddd {
            get {
                return this.dddField;
            }
            set {
                this.dddField = value;
                this.RaisePropertyChanged("ddd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone {
            get {
                return this.telefoneField;
            }
            set {
                this.telefoneField = value;
                this.RaisePropertyChanged("telefone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_pais {
            get {
                return this.codigo_paisField;
            }
            set {
                this.codigo_paisField = value;
                this.RaisePropertyChanged("codigo_pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string data_inc {
            get {
                return this.data_incField;
            }
            set {
                this.data_incField = value;
                this.RaisePropertyChanged("data_inc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hora_inc {
            get {
                return this.hora_incField;
            }
            set {
                this.hora_incField = value;
                this.RaisePropertyChanged("hora_inc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string user_inc {
            get {
                return this.user_incField;
            }
            set {
                this.user_incField = value;
                this.RaisePropertyChanged("user_inc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string data_alt {
            get {
                return this.data_altField;
            }
            set {
                this.data_altField = value;
                this.RaisePropertyChanged("data_alt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string hora_alt {
            get {
                return this.hora_altField;
            }
            set {
                this.hora_altField = value;
                this.RaisePropertyChanged("hora_alt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string user_alt {
            get {
                return this.user_altField;
            }
            set {
                this.user_altField = value;
                this.RaisePropertyChanged("user_alt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importado_api {
            get {
                return this.importado_apiField;
            }
            set {
                this.importado_apiField = value;
                this.RaisePropertyChanged("importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
                this.RaisePropertyChanged("bloqueado");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_lote_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loteField;
        
        private string cCodStatusField;
        
        private string cDesStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDesStatus {
            get {
                return this.cDesStatusField;
            }
            set {
                this.cDesStatusField = value;
                this.RaisePropertyChanged("cDesStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_lote_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loteField;
        
        private fin_conta_corrente_cadastro[] fin_conta_corrente_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public fin_conta_corrente_cadastro[] fin_conta_corrente_cadastro {
            get {
                return this.fin_conta_corrente_cadastroField;
            }
            set {
                this.fin_conta_corrente_cadastroField = value;
                this.RaisePropertyChanged("fin_conta_corrente_cadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class conta_corrente_lista : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodCCField;
        
        private string cCodCCIntField;
        
        private string descricaoField;
        
        private string codigo_bancoField;
        
        private string codigo_agenciaField;
        
        private string conta_correnteField;
        
        private string nome_gerenteField;
        
        private string tipoField;
        
        private string tipo_comunicacaoField;
        
        private string cSincrAnaliticaField;
        
        private string nTpTefField;
        
        private System.Nullable<decimal> nTaxaAdmField;
        
        private bool nTaxaAdmFieldSpecified;
        
        private string nDiasVencField;
        
        private string nNumParcField;
        
        private string nCodAdmField;
        
        private string cUtilPDVField;
        
        private string cModalidadeField;
        
        private System.Nullable<decimal> saldo_inicialField;
        
        private bool saldo_inicialFieldSpecified;
        
        private string saldo_dataField;
        
        private System.Nullable<decimal> valor_limiteField;
        
        private bool valor_limiteFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodCC {
            get {
                return this.nCodCCField;
            }
            set {
                this.nCodCCField = value;
                this.RaisePropertyChanged("nCodCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodCCInt {
            get {
                return this.cCodCCIntField;
            }
            set {
                this.cCodCCIntField = value;
                this.RaisePropertyChanged("cCodCCInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_banco {
            get {
                return this.codigo_bancoField;
            }
            set {
                this.codigo_bancoField = value;
                this.RaisePropertyChanged("codigo_banco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_agencia {
            get {
                return this.codigo_agenciaField;
            }
            set {
                this.codigo_agenciaField = value;
                this.RaisePropertyChanged("codigo_agencia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string conta_corrente {
            get {
                return this.conta_correnteField;
            }
            set {
                this.conta_correnteField = value;
                this.RaisePropertyChanged("conta_corrente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_gerente {
            get {
                return this.nome_gerenteField;
            }
            set {
                this.nome_gerenteField = value;
                this.RaisePropertyChanged("nome_gerente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipo_comunicacao {
            get {
                return this.tipo_comunicacaoField;
            }
            set {
                this.tipo_comunicacaoField = value;
                this.RaisePropertyChanged("tipo_comunicacao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cSincrAnalitica {
            get {
                return this.cSincrAnaliticaField;
            }
            set {
                this.cSincrAnaliticaField = value;
                this.RaisePropertyChanged("cSincrAnalitica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nTpTef {
            get {
                return this.nTpTefField;
            }
            set {
                this.nTpTefField = value;
                this.RaisePropertyChanged("nTpTef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> nTaxaAdm {
            get {
                return this.nTaxaAdmField;
            }
            set {
                this.nTaxaAdmField = value;
                this.RaisePropertyChanged("nTaxaAdm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool nTaxaAdmSpecified {
            get {
                return this.nTaxaAdmFieldSpecified;
            }
            set {
                this.nTaxaAdmFieldSpecified = value;
                this.RaisePropertyChanged("nTaxaAdmSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nDiasVenc {
            get {
                return this.nDiasVencField;
            }
            set {
                this.nDiasVencField = value;
                this.RaisePropertyChanged("nDiasVenc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nNumParc {
            get {
                return this.nNumParcField;
            }
            set {
                this.nNumParcField = value;
                this.RaisePropertyChanged("nNumParc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodAdm {
            get {
                return this.nCodAdmField;
            }
            set {
                this.nCodAdmField = value;
                this.RaisePropertyChanged("nCodAdm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cUtilPDV {
            get {
                return this.cUtilPDVField;
            }
            set {
                this.cUtilPDVField = value;
                this.RaisePropertyChanged("cUtilPDV");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cModalidade {
            get {
                return this.cModalidadeField;
            }
            set {
                this.cModalidadeField = value;
                this.RaisePropertyChanged("cModalidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> saldo_inicial {
            get {
                return this.saldo_inicialField;
            }
            set {
                this.saldo_inicialField = value;
                this.RaisePropertyChanged("saldo_inicial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool saldo_inicialSpecified {
            get {
                return this.saldo_inicialFieldSpecified;
            }
            set {
                this.saldo_inicialFieldSpecified = value;
                this.RaisePropertyChanged("saldo_inicialSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string saldo_data {
            get {
                return this.saldo_dataField;
            }
            set {
                this.saldo_dataField = value;
                this.RaisePropertyChanged("saldo_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor_limite {
            get {
                return this.valor_limiteField;
            }
            set {
                this.valor_limiteField = value;
                this.RaisePropertyChanged("valor_limite");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valor_limiteSpecified {
            get {
                return this.valor_limiteFieldSpecified;
            }
            set {
                this.valor_limiteFieldSpecified = value;
                this.RaisePropertyChanged("valor_limiteSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_pesquisar_resposta : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private conta_corrente_lista[] conta_corrente_listaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public conta_corrente_lista[] conta_corrente_lista {
            get {
                return this.conta_corrente_listaField;
            }
            set {
                this.conta_corrente_listaField = value;
                this.RaisePropertyChanged("conta_corrente_lista");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_pesquisar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codigo_integracaoField;
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_descrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_integracao {
            get {
                return this.codigo_integracaoField;
            }
            set {
                this.codigo_integracaoField = value;
                this.RaisePropertyChanged("codigo_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_chave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodCCField;
        
        private string cCodCCIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodCC {
            get {
                return this.nCodCCField;
            }
            set {
                this.nCodCCField = value;
                this.RaisePropertyChanged("nCodCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodCCInt {
            get {
                return this.cCodCCIntField;
            }
            set {
                this.cCodCCIntField = value;
                this.RaisePropertyChanged("cCodCCInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/contacorrente/?WSDL")]
    public partial class fin_conta_corrente_cadastro_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nCodCCField;
        
        private string cCodCCIntField;
        
        private string cCodStatusField;
        
        private string cDesStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodCC {
            get {
                return this.nCodCCField;
            }
            set {
                this.nCodCCField = value;
                this.RaisePropertyChanged("nCodCC");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodCCInt {
            get {
                return this.cCodCCIntField;
            }
            set {
                this.cCodCCIntField = value;
                this.RaisePropertyChanged("cCodCCInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDesStatus {
            get {
                return this.cDesStatusField;
            }
            set {
                this.cDesStatusField = value;
                this.RaisePropertyChanged("cDesStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ContaCorrenteCadastroSoapChannel : Sync.ContaCorrenteCadastroReference.ContaCorrenteCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ContaCorrenteCadastroSoapClient : System.ServiceModel.ClientBase<Sync.ContaCorrenteCadastroReference.ContaCorrenteCadastroSoap>, Sync.ContaCorrenteCadastroReference.ContaCorrenteCadastroSoap {
        
        public ContaCorrenteCadastroSoapClient() {
        }
        
        public ContaCorrenteCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ContaCorrenteCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContaCorrenteCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ContaCorrenteCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response IncluirContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.IncluirContaCorrente(fin_conta_corrente_cadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> IncluirContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.IncluirContaCorrenteAsync(fin_conta_corrente_cadastro);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response AlterarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.AlterarContaCorrente(fin_conta_corrente_cadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> AlterarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.AlterarContaCorrenteAsync(fin_conta_corrente_cadastro);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response ExcluirContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave) {
            return base.Channel.ExcluirContaCorrente(fin_conta_corrente_chave);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> ExcluirContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave) {
            return base.Channel.ExcluirContaCorrenteAsync(fin_conta_corrente_chave);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro ConsultarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave) {
            return base.Channel.ConsultarContaCorrente(fin_conta_corrente_chave);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro> ConsultarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_chave fin_conta_corrente_chave) {
            return base.Channel.ConsultarContaCorrenteAsync(fin_conta_corrente_chave);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar_resposta PesquisarContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar fin_conta_corrente_pesquisar) {
            return base.Channel.PesquisarContaCorrente(fin_conta_corrente_pesquisar);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar_resposta> PesquisarContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_pesquisar fin_conta_corrente_pesquisar) {
            return base.Channel.PesquisarContaCorrenteAsync(fin_conta_corrente_pesquisar);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response UpsertContaCorrente(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.UpsertContaCorrente(fin_conta_corrente_cadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro_response> UpsertContaCorrenteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_cadastro fin_conta_corrente_cadastro) {
            return base.Channel.UpsertContaCorrenteAsync(fin_conta_corrente_cadastro);
        }
        
        public Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_response UpsertContaCorrentePorLote(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_request fin_conta_corrente_lote_request) {
            return base.Channel.UpsertContaCorrentePorLote(fin_conta_corrente_lote_request);
        }
        
        public System.Threading.Tasks.Task<Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_response> UpsertContaCorrentePorLoteAsync(Sync.ContaCorrenteCadastroReference.fin_conta_corrente_lote_request fin_conta_corrente_lote_request) {
            return base.Channel.UpsertContaCorrentePorLoteAsync(fin_conta_corrente_lote_request);
        }
    }
}
