//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.EmpresaCadastroReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/empresas/?WSDL", ConfigurationName="EmpresaCadastroReference.EmpresasCadastroSoap")]
    public interface EmpresasCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/empresas/?WSDLConsultarEmpresa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="empresas_cadastro")]
        Sync.EmpresaCadastroReference.empresas_cadastro ConsultarEmpresa(Sync.EmpresaCadastroReference.empresas_consultar empresas_consultar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/empresas/?WSDLConsultarEmpresa", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="empresas_cadastro")]
        System.Threading.Tasks.Task<Sync.EmpresaCadastroReference.empresas_cadastro> ConsultarEmpresaAsync(Sync.EmpresaCadastroReference.empresas_consultar empresas_consultar);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/empresas/?WSDLListarEmpresas", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="empresas_list_response")]
        Sync.EmpresaCadastroReference.empresas_list_response ListarEmpresas(Sync.EmpresaCadastroReference.empresas_list_request empresas_list_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/empresas/?WSDLListarEmpresas", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="empresas_list_response")]
        System.Threading.Tasks.Task<Sync.EmpresaCadastroReference.empresas_list_response> ListarEmpresasAsync(Sync.EmpresaCadastroReference.empresas_list_request empresas_list_request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/empresas/?WSDL")]
    public partial class empresas_consultar : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_empresaField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_empresa {
            get {
                return this.codigo_empresaField;
            }
            set {
                this.codigo_empresaField = value;
                this.RaisePropertyChanged("codigo_empresa");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/empresas/?WSDL")]
    public partial class empresas_list_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private empresas_cadastro[] empresas_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public empresas_cadastro[] empresas_cadastro {
            get {
                return this.empresas_cadastroField;
            }
            set {
                this.empresas_cadastroField = value;
                this.RaisePropertyChanged("empresas_cadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/empresas/?WSDL")]
    public partial class empresas_cadastro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_empresaField;
        
        private string codigo_empresa_integracaoField;
        
        private string cnpjField;
        
        private string razao_socialField;
        
        private string nome_fantasiaField;
        
        private string logradouroField;
        
        private string enderecoField;
        
        private string endereco_numeroField;
        
        private string complementoField;
        
        private string bairroField;
        
        private string cidadeField;
        
        private string estadoField;
        
        private string cepField;
        
        private string codigo_paisField;
        
        private string data_adesao_snField;
        
        private string telefone1_dddField;
        
        private string telefone1_numeroField;
        
        private string telefone2_dddField;
        
        private string telefone2_numeroField;
        
        private string fax_dddField;
        
        private string fax_numeroField;
        
        private string emailField;
        
        private string websiteField;
        
        private string cnaeField;
        
        private string cnae_municipalField;
        
        private string inscricao_estadualField;
        
        private string inscricao_municipalField;
        
        private string inscricao_suframaField;
        
        private string regime_tributarioField;
        
        private string inativaField;
        
        private string gera_nfseField;
        
        private string optante_simples_nacionalField;
        
        private string sped_codigo_incidencia_tributariaField;
        
        private string sped_codigo_tipo_contribuicaoField;
        
        private string sped_cpf_contadorField;
        
        private string sped_crc_contadorField;
        
        private string sped_usa_contabilidade_terceirizadaField;
        
        private string sped_email_contadorField;
        
        private string sped_codigo_indicador_apropriacao_creditoField;
        
        private string sped_codigo_tipo_atividadeField;
        
        private string sped_natureza_pessoa_juridicaField;
        
        private string sped_codigo_criterio_escrituracaoField;
        
        private string sped_junta_comercialField;
        
        private string sped_matrizField;
        
        private string sped_nome_contadorField;
        
        private string sped_registro_junta_comercialField;
        
        private string efd_atividade_industrialField;
        
        private string efd_perfil_arquivo_fiscalField;
        
        private string ecd_codigo_cadastralField;
        
        private string ecd_codigo_instituicao_responsavelField;
        
        private string gera_nfeField;
        
        private string inclusao_dataField;
        
        private string inclusao_horaField;
        
        private string alteracao_dataField;
        
        private string alteracao_horaField;
        
        private string bloqueadoField;
        
        private string pdv_sincr_analiticaField;
        
        private string importado_apiField;
        
        private string dt_adesao_simpnacField;
        
        private string ie_stField;
        
        private string recibo_ideField;
        
        private string gera_reciboField;
        
        private string recibo_tipoField;
        
        private string recibo_num_viasField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_empresa {
            get {
                return this.codigo_empresaField;
            }
            set {
                this.codigo_empresaField = value;
                this.RaisePropertyChanged("codigo_empresa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_empresa_integracao {
            get {
                return this.codigo_empresa_integracaoField;
            }
            set {
                this.codigo_empresa_integracaoField = value;
                this.RaisePropertyChanged("codigo_empresa_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnpj {
            get {
                return this.cnpjField;
            }
            set {
                this.cnpjField = value;
                this.RaisePropertyChanged("cnpj");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string razao_social {
            get {
                return this.razao_socialField;
            }
            set {
                this.razao_socialField = value;
                this.RaisePropertyChanged("razao_social");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome_fantasia {
            get {
                return this.nome_fantasiaField;
            }
            set {
                this.nome_fantasiaField = value;
                this.RaisePropertyChanged("nome_fantasia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string logradouro {
            get {
                return this.logradouroField;
            }
            set {
                this.logradouroField = value;
                this.RaisePropertyChanged("logradouro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco {
            get {
                return this.enderecoField;
            }
            set {
                this.enderecoField = value;
                this.RaisePropertyChanged("endereco");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string endereco_numero {
            get {
                return this.endereco_numeroField;
            }
            set {
                this.endereco_numeroField = value;
                this.RaisePropertyChanged("endereco_numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string complemento {
            get {
                return this.complementoField;
            }
            set {
                this.complementoField = value;
                this.RaisePropertyChanged("complemento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bairro {
            get {
                return this.bairroField;
            }
            set {
                this.bairroField = value;
                this.RaisePropertyChanged("bairro");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cidade {
            get {
                return this.cidadeField;
            }
            set {
                this.cidadeField = value;
                this.RaisePropertyChanged("cidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cep {
            get {
                return this.cepField;
            }
            set {
                this.cepField = value;
                this.RaisePropertyChanged("cep");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_pais {
            get {
                return this.codigo_paisField;
            }
            set {
                this.codigo_paisField = value;
                this.RaisePropertyChanged("codigo_pais");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string data_adesao_sn {
            get {
                return this.data_adesao_snField;
            }
            set {
                this.data_adesao_snField = value;
                this.RaisePropertyChanged("data_adesao_sn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone1_ddd {
            get {
                return this.telefone1_dddField;
            }
            set {
                this.telefone1_dddField = value;
                this.RaisePropertyChanged("telefone1_ddd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone1_numero {
            get {
                return this.telefone1_numeroField;
            }
            set {
                this.telefone1_numeroField = value;
                this.RaisePropertyChanged("telefone1_numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone2_ddd {
            get {
                return this.telefone2_dddField;
            }
            set {
                this.telefone2_dddField = value;
                this.RaisePropertyChanged("telefone2_ddd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string telefone2_numero {
            get {
                return this.telefone2_numeroField;
            }
            set {
                this.telefone2_numeroField = value;
                this.RaisePropertyChanged("telefone2_numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax_ddd {
            get {
                return this.fax_dddField;
            }
            set {
                this.fax_dddField = value;
                this.RaisePropertyChanged("fax_ddd");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fax_numero {
            get {
                return this.fax_numeroField;
            }
            set {
                this.fax_numeroField = value;
                this.RaisePropertyChanged("fax_numero");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string email {
            get {
                return this.emailField;
            }
            set {
                this.emailField = value;
                this.RaisePropertyChanged("email");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string website {
            get {
                return this.websiteField;
            }
            set {
                this.websiteField = value;
                this.RaisePropertyChanged("website");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnae {
            get {
                return this.cnaeField;
            }
            set {
                this.cnaeField = value;
                this.RaisePropertyChanged("cnae");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cnae_municipal {
            get {
                return this.cnae_municipalField;
            }
            set {
                this.cnae_municipalField = value;
                this.RaisePropertyChanged("cnae_municipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_estadual {
            get {
                return this.inscricao_estadualField;
            }
            set {
                this.inscricao_estadualField = value;
                this.RaisePropertyChanged("inscricao_estadual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_municipal {
            get {
                return this.inscricao_municipalField;
            }
            set {
                this.inscricao_municipalField = value;
                this.RaisePropertyChanged("inscricao_municipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inscricao_suframa {
            get {
                return this.inscricao_suframaField;
            }
            set {
                this.inscricao_suframaField = value;
                this.RaisePropertyChanged("inscricao_suframa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string regime_tributario {
            get {
                return this.regime_tributarioField;
            }
            set {
                this.regime_tributarioField = value;
                this.RaisePropertyChanged("regime_tributario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativa {
            get {
                return this.inativaField;
            }
            set {
                this.inativaField = value;
                this.RaisePropertyChanged("inativa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gera_nfse {
            get {
                return this.gera_nfseField;
            }
            set {
                this.gera_nfseField = value;
                this.RaisePropertyChanged("gera_nfse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string optante_simples_nacional {
            get {
                return this.optante_simples_nacionalField;
            }
            set {
                this.optante_simples_nacionalField = value;
                this.RaisePropertyChanged("optante_simples_nacional");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_codigo_incidencia_tributaria {
            get {
                return this.sped_codigo_incidencia_tributariaField;
            }
            set {
                this.sped_codigo_incidencia_tributariaField = value;
                this.RaisePropertyChanged("sped_codigo_incidencia_tributaria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_codigo_tipo_contribuicao {
            get {
                return this.sped_codigo_tipo_contribuicaoField;
            }
            set {
                this.sped_codigo_tipo_contribuicaoField = value;
                this.RaisePropertyChanged("sped_codigo_tipo_contribuicao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_cpf_contador {
            get {
                return this.sped_cpf_contadorField;
            }
            set {
                this.sped_cpf_contadorField = value;
                this.RaisePropertyChanged("sped_cpf_contador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_crc_contador {
            get {
                return this.sped_crc_contadorField;
            }
            set {
                this.sped_crc_contadorField = value;
                this.RaisePropertyChanged("sped_crc_contador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_usa_contabilidade_terceirizada {
            get {
                return this.sped_usa_contabilidade_terceirizadaField;
            }
            set {
                this.sped_usa_contabilidade_terceirizadaField = value;
                this.RaisePropertyChanged("sped_usa_contabilidade_terceirizada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_email_contador {
            get {
                return this.sped_email_contadorField;
            }
            set {
                this.sped_email_contadorField = value;
                this.RaisePropertyChanged("sped_email_contador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_codigo_indicador_apropriacao_credito {
            get {
                return this.sped_codigo_indicador_apropriacao_creditoField;
            }
            set {
                this.sped_codigo_indicador_apropriacao_creditoField = value;
                this.RaisePropertyChanged("sped_codigo_indicador_apropriacao_credito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_codigo_tipo_atividade {
            get {
                return this.sped_codigo_tipo_atividadeField;
            }
            set {
                this.sped_codigo_tipo_atividadeField = value;
                this.RaisePropertyChanged("sped_codigo_tipo_atividade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_natureza_pessoa_juridica {
            get {
                return this.sped_natureza_pessoa_juridicaField;
            }
            set {
                this.sped_natureza_pessoa_juridicaField = value;
                this.RaisePropertyChanged("sped_natureza_pessoa_juridica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_codigo_criterio_escrituracao {
            get {
                return this.sped_codigo_criterio_escrituracaoField;
            }
            set {
                this.sped_codigo_criterio_escrituracaoField = value;
                this.RaisePropertyChanged("sped_codigo_criterio_escrituracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_junta_comercial {
            get {
                return this.sped_junta_comercialField;
            }
            set {
                this.sped_junta_comercialField = value;
                this.RaisePropertyChanged("sped_junta_comercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_matriz {
            get {
                return this.sped_matrizField;
            }
            set {
                this.sped_matrizField = value;
                this.RaisePropertyChanged("sped_matriz");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_nome_contador {
            get {
                return this.sped_nome_contadorField;
            }
            set {
                this.sped_nome_contadorField = value;
                this.RaisePropertyChanged("sped_nome_contador");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string sped_registro_junta_comercial {
            get {
                return this.sped_registro_junta_comercialField;
            }
            set {
                this.sped_registro_junta_comercialField = value;
                this.RaisePropertyChanged("sped_registro_junta_comercial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string efd_atividade_industrial {
            get {
                return this.efd_atividade_industrialField;
            }
            set {
                this.efd_atividade_industrialField = value;
                this.RaisePropertyChanged("efd_atividade_industrial");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string efd_perfil_arquivo_fiscal {
            get {
                return this.efd_perfil_arquivo_fiscalField;
            }
            set {
                this.efd_perfil_arquivo_fiscalField = value;
                this.RaisePropertyChanged("efd_perfil_arquivo_fiscal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ecd_codigo_cadastral {
            get {
                return this.ecd_codigo_cadastralField;
            }
            set {
                this.ecd_codigo_cadastralField = value;
                this.RaisePropertyChanged("ecd_codigo_cadastral");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ecd_codigo_instituicao_responsavel {
            get {
                return this.ecd_codigo_instituicao_responsavelField;
            }
            set {
                this.ecd_codigo_instituicao_responsavelField = value;
                this.RaisePropertyChanged("ecd_codigo_instituicao_responsavel");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gera_nfe {
            get {
                return this.gera_nfeField;
            }
            set {
                this.gera_nfeField = value;
                this.RaisePropertyChanged("gera_nfe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inclusao_data {
            get {
                return this.inclusao_dataField;
            }
            set {
                this.inclusao_dataField = value;
                this.RaisePropertyChanged("inclusao_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inclusao_hora {
            get {
                return this.inclusao_horaField;
            }
            set {
                this.inclusao_horaField = value;
                this.RaisePropertyChanged("inclusao_hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string alteracao_data {
            get {
                return this.alteracao_dataField;
            }
            set {
                this.alteracao_dataField = value;
                this.RaisePropertyChanged("alteracao_data");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string alteracao_hora {
            get {
                return this.alteracao_horaField;
            }
            set {
                this.alteracao_horaField = value;
                this.RaisePropertyChanged("alteracao_hora");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
                this.RaisePropertyChanged("bloqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string pdv_sincr_analitica {
            get {
                return this.pdv_sincr_analiticaField;
            }
            set {
                this.pdv_sincr_analiticaField = value;
                this.RaisePropertyChanged("pdv_sincr_analitica");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importado_api {
            get {
                return this.importado_apiField;
            }
            set {
                this.importado_apiField = value;
                this.RaisePropertyChanged("importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string dt_adesao_simpnac {
            get {
                return this.dt_adesao_simpnacField;
            }
            set {
                this.dt_adesao_simpnacField = value;
                this.RaisePropertyChanged("dt_adesao_simpnac");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ie_st {
            get {
                return this.ie_stField;
            }
            set {
                this.ie_stField = value;
                this.RaisePropertyChanged("ie_st");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recibo_ide {
            get {
                return this.recibo_ideField;
            }
            set {
                this.recibo_ideField = value;
                this.RaisePropertyChanged("recibo_ide");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string gera_recibo {
            get {
                return this.gera_reciboField;
            }
            set {
                this.gera_reciboField = value;
                this.RaisePropertyChanged("gera_recibo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recibo_tipo {
            get {
                return this.recibo_tipoField;
            }
            set {
                this.recibo_tipoField = value;
                this.RaisePropertyChanged("recibo_tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string recibo_num_vias {
            get {
                return this.recibo_num_viasField;
            }
            set {
                this.recibo_num_viasField = value;
                this.RaisePropertyChanged("recibo_num_vias");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/empresas/?WSDL")]
    public partial class empresas_list_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_descrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface EmpresasCadastroSoapChannel : Sync.EmpresaCadastroReference.EmpresasCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class EmpresasCadastroSoapClient : System.ServiceModel.ClientBase<Sync.EmpresaCadastroReference.EmpresasCadastroSoap>, Sync.EmpresaCadastroReference.EmpresasCadastroSoap {
        
        public EmpresasCadastroSoapClient() {
        }
        
        public EmpresasCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public EmpresasCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public EmpresasCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.EmpresaCadastroReference.empresas_cadastro ConsultarEmpresa(Sync.EmpresaCadastroReference.empresas_consultar empresas_consultar) {
            return base.Channel.ConsultarEmpresa(empresas_consultar);
        }
        
        public System.Threading.Tasks.Task<Sync.EmpresaCadastroReference.empresas_cadastro> ConsultarEmpresaAsync(Sync.EmpresaCadastroReference.empresas_consultar empresas_consultar) {
            return base.Channel.ConsultarEmpresaAsync(empresas_consultar);
        }
        
        public Sync.EmpresaCadastroReference.empresas_list_response ListarEmpresas(Sync.EmpresaCadastroReference.empresas_list_request empresas_list_request) {
            return base.Channel.ListarEmpresas(empresas_list_request);
        }
        
        public System.Threading.Tasks.Task<Sync.EmpresaCadastroReference.empresas_list_response> ListarEmpresasAsync(Sync.EmpresaCadastroReference.empresas_list_request empresas_list_request) {
            return base.Channel.ListarEmpresasAsync(empresas_list_request);
        }
    }
}
