//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.VendedoresCadastroReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL", ConfigurationName="VendedoresCadastroReference.VendedoresCadastroSoap")]
    public interface VendedoresCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLIncluirVendedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendIncluirResponse")]
        Sync.VendedoresCadastroReference.vendIncluirResponse IncluirVendedor(Sync.VendedoresCadastroReference.vendincluirRequest vendincluirRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLIncluirVendedor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendIncluirResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendIncluirResponse> IncluirVendedorAsync(Sync.VendedoresCadastroReference.vendincluirRequest vendincluirRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLAlterarVendedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendAlterarResponse")]
        Sync.VendedoresCadastroReference.vendAlterarResponse AlterarVendedor(Sync.VendedoresCadastroReference.vendAlterarRequest vendAlterarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLAlterarVendedor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendAlterarResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendAlterarResponse> AlterarVendedorAsync(Sync.VendedoresCadastroReference.vendAlterarRequest vendAlterarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLUpsertVendedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendUpsertResponse")]
        Sync.VendedoresCadastroReference.vendUpsertResponse UpsertVendedor(Sync.VendedoresCadastroReference.vendUpsertRequest vendUpsertRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLUpsertVendedor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendUpsertResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendUpsertResponse> UpsertVendedorAsync(Sync.VendedoresCadastroReference.vendUpsertRequest vendUpsertRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLExcluirVendedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendExcluirResponse")]
        Sync.VendedoresCadastroReference.vendExcluirResponse ExcluirVendedor(Sync.VendedoresCadastroReference.vendExcluirRequest vendExcluirRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLExcluirVendedor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendExcluirResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendExcluirResponse> ExcluirVendedorAsync(Sync.VendedoresCadastroReference.vendExcluirRequest vendExcluirRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLConsultarVendedor", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendConsultarResponse")]
        Sync.VendedoresCadastroReference.vendConsultarResponse ConsultarVendedor(Sync.VendedoresCadastroReference.vendConsultarRequest vendConsultarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLConsultarVendedor", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendConsultarResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendConsultarResponse> ConsultarVendedorAsync(Sync.VendedoresCadastroReference.vendConsultarRequest vendConsultarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLListarVendedores", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastro))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendListarResponse")]
        Sync.VendedoresCadastroReference.vendListarResponse ListarVendedores(Sync.VendedoresCadastroReference.vendListarRequest vendListarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/vendedores/?WSDLListarVendedores", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="vendListarResponse")]
        System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendListarResponse> ListarVendedoresAsync(Sync.VendedoresCadastroReference.vendListarRequest vendListarRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendincluirRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codIntField;
        
        private string nomeField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class cadastro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string nomeField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendListarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private cadastro[] cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cadastro[] cadastro {
            get {
                return this.cadastroField;
            }
            set {
                this.cadastroField = value;
                this.RaisePropertyChanged("cadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendListarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_descrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendConsultarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string nomeField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendConsultarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendExcluirResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendExcluirRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendUpsertResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendUpsertRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string nomeField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendAlterarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendAlterarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string nomeField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nome {
            get {
                return this.nomeField;
            }
            set {
                this.nomeField = value;
                this.RaisePropertyChanged("nome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/vendedores/?WSDL")]
    public partial class vendIncluirResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string statusField;
        
        private string descricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface VendedoresCadastroSoapChannel : Sync.VendedoresCadastroReference.VendedoresCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class VendedoresCadastroSoapClient : System.ServiceModel.ClientBase<Sync.VendedoresCadastroReference.VendedoresCadastroSoap>, Sync.VendedoresCadastroReference.VendedoresCadastroSoap {
        
        public VendedoresCadastroSoapClient() {
        }
        
        public VendedoresCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public VendedoresCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedoresCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public VendedoresCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.VendedoresCadastroReference.vendIncluirResponse IncluirVendedor(Sync.VendedoresCadastroReference.vendincluirRequest vendincluirRequest) {
            return base.Channel.IncluirVendedor(vendincluirRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendIncluirResponse> IncluirVendedorAsync(Sync.VendedoresCadastroReference.vendincluirRequest vendincluirRequest) {
            return base.Channel.IncluirVendedorAsync(vendincluirRequest);
        }
        
        public Sync.VendedoresCadastroReference.vendAlterarResponse AlterarVendedor(Sync.VendedoresCadastroReference.vendAlterarRequest vendAlterarRequest) {
            return base.Channel.AlterarVendedor(vendAlterarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendAlterarResponse> AlterarVendedorAsync(Sync.VendedoresCadastroReference.vendAlterarRequest vendAlterarRequest) {
            return base.Channel.AlterarVendedorAsync(vendAlterarRequest);
        }
        
        public Sync.VendedoresCadastroReference.vendUpsertResponse UpsertVendedor(Sync.VendedoresCadastroReference.vendUpsertRequest vendUpsertRequest) {
            return base.Channel.UpsertVendedor(vendUpsertRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendUpsertResponse> UpsertVendedorAsync(Sync.VendedoresCadastroReference.vendUpsertRequest vendUpsertRequest) {
            return base.Channel.UpsertVendedorAsync(vendUpsertRequest);
        }
        
        public Sync.VendedoresCadastroReference.vendExcluirResponse ExcluirVendedor(Sync.VendedoresCadastroReference.vendExcluirRequest vendExcluirRequest) {
            return base.Channel.ExcluirVendedor(vendExcluirRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendExcluirResponse> ExcluirVendedorAsync(Sync.VendedoresCadastroReference.vendExcluirRequest vendExcluirRequest) {
            return base.Channel.ExcluirVendedorAsync(vendExcluirRequest);
        }
        
        public Sync.VendedoresCadastroReference.vendConsultarResponse ConsultarVendedor(Sync.VendedoresCadastroReference.vendConsultarRequest vendConsultarRequest) {
            return base.Channel.ConsultarVendedor(vendConsultarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendConsultarResponse> ConsultarVendedorAsync(Sync.VendedoresCadastroReference.vendConsultarRequest vendConsultarRequest) {
            return base.Channel.ConsultarVendedorAsync(vendConsultarRequest);
        }
        
        public Sync.VendedoresCadastroReference.vendListarResponse ListarVendedores(Sync.VendedoresCadastroReference.vendListarRequest vendListarRequest) {
            return base.Channel.ListarVendedores(vendListarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.VendedoresCadastroReference.vendListarResponse> ListarVendedoresAsync(Sync.VendedoresCadastroReference.vendListarRequest vendListarRequest) {
            return base.Channel.ListarVendedoresAsync(vendListarRequest);
        }
    }
}
