//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.FamiliasProdutoReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL", ConfigurationName="FamiliasProdutoReference.FamiliasCadastroSoap")]
    public interface FamiliasCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLGetVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        string GetVersion();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLGetVersion", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="string")]
        System.Threading.Tasks.Task<string> GetVersionAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLIncluirFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        Sync.FamiliasProdutoReference.famStatus IncluirFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLIncluirFamilia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> IncluirFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLAlterarFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        Sync.FamiliasProdutoReference.famStatus AlterarFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLAlterarFamilia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> AlterarFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLUpsertFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        Sync.FamiliasProdutoReference.famStatus UpsertFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLUpsertFamilia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> UpsertFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLExcluirFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        Sync.FamiliasProdutoReference.famStatus ExcluirFamilia(Sync.FamiliasProdutoReference.famChave famChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLExcluirFamilia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famStatus")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> ExcluirFamiliaAsync(Sync.FamiliasProdutoReference.famChave famChave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLConsultarFamilia", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famConsultarResponse")]
        Sync.FamiliasProdutoReference.famConsultarResponse ConsultarFamilia(Sync.FamiliasProdutoReference.famConsultarRequest famConsultarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLConsultarFamilia", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famConsultarResponse")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famConsultarResponse> ConsultarFamiliaAsync(Sync.FamiliasProdutoReference.famConsultarRequest famConsultarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLPesquisarFamilias", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famListarResponse")]
        Sync.FamiliasProdutoReference.famListarResponse PesquisarFamilias(Sync.FamiliasProdutoReference.famListarRequest famListarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/familias/?WSDLPesquisarFamilias", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="famListarResponse")]
        System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famListarResponse> PesquisarFamiliasAsync(Sync.FamiliasProdutoReference.famListarRequest famListarRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famCadastro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string codFamiliaField;
        
        private string nomeFamiliaField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codFamilia {
            get {
                return this.codFamiliaField;
            }
            set {
                this.codFamiliaField = value;
                this.RaisePropertyChanged("codFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeFamilia {
            get {
                return this.nomeFamiliaField;
            }
            set {
                this.nomeFamiliaField = value;
                this.RaisePropertyChanged("nomeFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famListarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private famCadastro[] famCadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public famCadastro[] famCadastro {
            get {
                return this.famCadastroField;
            }
            set {
                this.famCadastroField = value;
                this.RaisePropertyChanged("famCadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famListarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_descrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer")]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famConsultarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string codFamiliaField;
        
        private string nomeFamiliaField;
        
        private string inativoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codFamilia {
            get {
                return this.codFamiliaField;
            }
            set {
                this.codFamiliaField = value;
                this.RaisePropertyChanged("codFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nomeFamilia {
            get {
                return this.nomeFamiliaField;
            }
            set {
                this.nomeFamiliaField = value;
                this.RaisePropertyChanged("nomeFamilia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famConsultarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famChave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.2046.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/familias/?WSDL")]
    public partial class famStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigoField;
        
        private string codIntField;
        
        private string cCodStatusField;
        
        private string cDesStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt {
            get {
                return this.codIntField;
            }
            set {
                this.codIntField = value;
                this.RaisePropertyChanged("codInt");
            }
        }
        
        /// <remarks/>
        public string cCodStatus {
            get {
                return this.cCodStatusField;
            }
            set {
                this.cCodStatusField = value;
                this.RaisePropertyChanged("cCodStatus");
            }
        }
        
        /// <remarks/>
        public string cDesStatus {
            get {
                return this.cDesStatusField;
            }
            set {
                this.cDesStatusField = value;
                this.RaisePropertyChanged("cDesStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FamiliasCadastroSoapChannel : Sync.FamiliasProdutoReference.FamiliasCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FamiliasCadastroSoapClient : System.ServiceModel.ClientBase<Sync.FamiliasProdutoReference.FamiliasCadastroSoap>, Sync.FamiliasProdutoReference.FamiliasCadastroSoap {
        
        public FamiliasCadastroSoapClient() {
        }
        
        public FamiliasCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FamiliasCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliasCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FamiliasCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetVersion() {
            return base.Channel.GetVersion();
        }
        
        public System.Threading.Tasks.Task<string> GetVersionAsync() {
            return base.Channel.GetVersionAsync();
        }
        
        public Sync.FamiliasProdutoReference.famStatus IncluirFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.IncluirFamilia(famCadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> IncluirFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.IncluirFamiliaAsync(famCadastro);
        }
        
        public Sync.FamiliasProdutoReference.famStatus AlterarFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.AlterarFamilia(famCadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> AlterarFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.AlterarFamiliaAsync(famCadastro);
        }
        
        public Sync.FamiliasProdutoReference.famStatus UpsertFamilia(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.UpsertFamilia(famCadastro);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> UpsertFamiliaAsync(Sync.FamiliasProdutoReference.famCadastro famCadastro) {
            return base.Channel.UpsertFamiliaAsync(famCadastro);
        }
        
        public Sync.FamiliasProdutoReference.famStatus ExcluirFamilia(Sync.FamiliasProdutoReference.famChave famChave) {
            return base.Channel.ExcluirFamilia(famChave);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famStatus> ExcluirFamiliaAsync(Sync.FamiliasProdutoReference.famChave famChave) {
            return base.Channel.ExcluirFamiliaAsync(famChave);
        }
        
        public Sync.FamiliasProdutoReference.famConsultarResponse ConsultarFamilia(Sync.FamiliasProdutoReference.famConsultarRequest famConsultarRequest) {
            return base.Channel.ConsultarFamilia(famConsultarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famConsultarResponse> ConsultarFamiliaAsync(Sync.FamiliasProdutoReference.famConsultarRequest famConsultarRequest) {
            return base.Channel.ConsultarFamiliaAsync(famConsultarRequest);
        }
        
        public Sync.FamiliasProdutoReference.famListarResponse PesquisarFamilias(Sync.FamiliasProdutoReference.famListarRequest famListarRequest) {
            return base.Channel.PesquisarFamilias(famListarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.FamiliasProdutoReference.famListarResponse> PesquisarFamiliasAsync(Sync.FamiliasProdutoReference.famListarRequest famListarRequest) {
            return base.Channel.PesquisarFamiliasAsync(famListarRequest);
        }
    }
}
