//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.FormaPagVendasReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDL", ConfigurationName="FormaPagVendasReference.FormasPagVendasSoap")]
    public interface FormasPagVendasSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDLListarFormasPagVendas" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(cadastros))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="venparListarResponse")]
        Sync.FormaPagVendasReference.venparListarResponse ListarFormasPagVendas(Sync.FormaPagVendasReference.venparListarRequest venparListarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDLListarFormasPagVendas" +
            "", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="venparListarResponse")]
        System.Threading.Tasks.Task<Sync.FormaPagVendasReference.venparListarResponse> ListarFormasPagVendasAsync(Sync.FormaPagVendasReference.venparListarRequest venparListarRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDL")]
    public partial class venparListarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string ordenar_porField;
        
        private string ordem_decrescenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_decrescente {
            get {
                return this.ordem_decrescenteField;
            }
            set {
                this.ordem_decrescenteField = value;
                this.RaisePropertyChanged("ordem_decrescente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDL")]
    public partial class cadastros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCodigoField;
        
        private string nQtdeParcField;
        
        private string cDescricaoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCodigo {
            get {
                return this.cCodigoField;
            }
            set {
                this.cCodigoField = value;
                this.RaisePropertyChanged("cCodigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nQtdeParc {
            get {
                return this.nQtdeParcField;
            }
            set {
                this.nQtdeParcField = value;
                this.RaisePropertyChanged("nQtdeParc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cDescricao {
            get {
                return this.cDescricaoField;
            }
            set {
                this.cDescricaoField = value;
                this.RaisePropertyChanged("cDescricao");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/produtos/formaspagvendas/?WSDL")]
    public partial class venparListarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private cadastros[] cadastrosField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public cadastros[] cadastros {
            get {
                return this.cadastrosField;
            }
            set {
                this.cadastrosField = value;
                this.RaisePropertyChanged("cadastros");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FormasPagVendasSoapChannel : Sync.FormaPagVendasReference.FormasPagVendasSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormasPagVendasSoapClient : System.ServiceModel.ClientBase<Sync.FormaPagVendasReference.FormasPagVendasSoap>, Sync.FormaPagVendasReference.FormasPagVendasSoap {
        
        public FormasPagVendasSoapClient() {
        }
        
        public FormasPagVendasSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormasPagVendasSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormasPagVendasSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormasPagVendasSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.FormaPagVendasReference.venparListarResponse ListarFormasPagVendas(Sync.FormaPagVendasReference.venparListarRequest venparListarRequest) {
            return base.Channel.ListarFormasPagVendas(venparListarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.FormaPagVendasReference.venparListarResponse> ListarFormasPagVendasAsync(Sync.FormaPagVendasReference.venparListarRequest venparListarRequest) {
            return base.Channel.ListarFormasPagVendasAsync(venparListarRequest);
        }
    }
}
