//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.ProdutosCadastroReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL", ConfigurationName="ProdutosCadastroReference.ProdutosCadastroSoap")]
    public interface ProdutosCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLIncluirProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_status")]
        Sync.ProdutosCadastroReference.produto_servico_status IncluirProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLAlterarProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_status")]
        Sync.ProdutosCadastroReference.produto_servico_status AlterarProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLExcluirProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_status")]
        Sync.ProdutosCadastroReference.produto_servico_status ExcluirProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro_chave produto_servico_cadastro_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLConsultarProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_cadastro")]
        Sync.ProdutosCadastroReference.produto_servico_cadastro ConsultarProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro_chave produto_servico_cadastro_chave);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLIncluirProdutosPorLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_lote_response")]
        Sync.ProdutosCadastroReference.produto_servico_lote_response IncluirProdutosPorLote(Sync.ProdutosCadastroReference.produto_servico_lote_request produto_servico_lote_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLListarProdutos", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_listfull_response")]
        Sync.ProdutosCadastroReference.produto_servico_listfull_response ListarProdutos(Sync.ProdutosCadastroReference.produto_servico_list_request produto_servico_list_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLListarProdutosResumido", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_list_response")]
        Sync.ProdutosCadastroReference.produto_servico_list_response ListarProdutosResumido(Sync.ProdutosCadastroReference.produto_servico_list_request produto_servico_list_request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLUpsertProduto", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_status")]
        Sync.ProdutosCadastroReference.produto_servico_status UpsertProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/produtos/?WSDLUpsertProdutosPorLote", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(produto_servico_resumido))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="produto_servico_lote_response")]
        Sync.ProdutosCadastroReference.produto_servico_lote_response UpsertProdutosPorLote(Sync.ProdutosCadastroReference.produto_servico_lote_request produto_servico_lote_request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_cadastro : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_produtoField;
        
        private string codigo_produto_integracaoField;
        
        private string codigoField;
        
        private string descricaoField;
        
        private string eanField;
        
        private string ncmField;
        
        private System.Nullable<decimal> quantidade_estoqueField;
        
        private bool quantidade_estoqueFieldSpecified;
        
        private string csosn_icmsField;
        
        private string unidadeField;
        
        private System.Nullable<decimal> valor_unitarioField;
        
        private bool valor_unitarioFieldSpecified;
        
        private string cst_icmsField;
        
        private System.Nullable<decimal> aliquota_icmsField;
        
        private bool aliquota_icmsFieldSpecified;
        
        private System.Nullable<decimal> red_base_icmsField;
        
        private bool red_base_icmsFieldSpecified;
        
        private System.Nullable<decimal> aliquota_ibptField;
        
        private bool aliquota_ibptFieldSpecified;
        
        private string tipoItemField;
        
        private string cst_pisField;
        
        private System.Nullable<decimal> aliquota_pisField;
        
        private bool aliquota_pisFieldSpecified;
        
        private string cst_cofinsField;
        
        private System.Nullable<decimal> aliquota_cofinsField;
        
        private bool aliquota_cofinsFieldSpecified;
        
        private string bloqueadoField;
        
        private string importado_apiField;
        
        private string codigo_familiaField;
        
        private string codInt_familiaField;
        
        private string descricao_familiaField;
        
        private string inativoField;
        
        private dadosIbpt dadosIbptField;
        
        private string cestField;
        
        private string cfopField;
        
        private System.Nullable<decimal> peso_liqField;
        
        private bool peso_liqFieldSpecified;
        
        private System.Nullable<decimal> peso_brutoField;
        
        private bool peso_brutoFieldSpecified;
        
        private System.Nullable<decimal> estoque_minimoField;
        
        private bool estoque_minimoFieldSpecified;
        
        private string descr_detalhadaField;
        
        private string obs_internasField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_produto {
            get {
                return this.codigo_produtoField;
            }
            set {
                this.codigo_produtoField = value;
                this.RaisePropertyChanged("codigo_produto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_produto_integracao {
            get {
                return this.codigo_produto_integracaoField;
            }
            set {
                this.codigo_produto_integracaoField = value;
                this.RaisePropertyChanged("codigo_produto_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ean {
            get {
                return this.eanField;
            }
            set {
                this.eanField = value;
                this.RaisePropertyChanged("ean");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ncm {
            get {
                return this.ncmField;
            }
            set {
                this.ncmField = value;
                this.RaisePropertyChanged("ncm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> quantidade_estoque {
            get {
                return this.quantidade_estoqueField;
            }
            set {
                this.quantidade_estoqueField = value;
                this.RaisePropertyChanged("quantidade_estoque");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool quantidade_estoqueSpecified {
            get {
                return this.quantidade_estoqueFieldSpecified;
            }
            set {
                this.quantidade_estoqueFieldSpecified = value;
                this.RaisePropertyChanged("quantidade_estoqueSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string csosn_icms {
            get {
                return this.csosn_icmsField;
            }
            set {
                this.csosn_icmsField = value;
                this.RaisePropertyChanged("csosn_icms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string unidade {
            get {
                return this.unidadeField;
            }
            set {
                this.unidadeField = value;
                this.RaisePropertyChanged("unidade");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor_unitario {
            get {
                return this.valor_unitarioField;
            }
            set {
                this.valor_unitarioField = value;
                this.RaisePropertyChanged("valor_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valor_unitarioSpecified {
            get {
                return this.valor_unitarioFieldSpecified;
            }
            set {
                this.valor_unitarioFieldSpecified = value;
                this.RaisePropertyChanged("valor_unitarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cst_icms {
            get {
                return this.cst_icmsField;
            }
            set {
                this.cst_icmsField = value;
                this.RaisePropertyChanged("cst_icms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliquota_icms {
            get {
                return this.aliquota_icmsField;
            }
            set {
                this.aliquota_icmsField = value;
                this.RaisePropertyChanged("aliquota_icms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliquota_icmsSpecified {
            get {
                return this.aliquota_icmsFieldSpecified;
            }
            set {
                this.aliquota_icmsFieldSpecified = value;
                this.RaisePropertyChanged("aliquota_icmsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> red_base_icms {
            get {
                return this.red_base_icmsField;
            }
            set {
                this.red_base_icmsField = value;
                this.RaisePropertyChanged("red_base_icms");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool red_base_icmsSpecified {
            get {
                return this.red_base_icmsFieldSpecified;
            }
            set {
                this.red_base_icmsFieldSpecified = value;
                this.RaisePropertyChanged("red_base_icmsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliquota_ibpt {
            get {
                return this.aliquota_ibptField;
            }
            set {
                this.aliquota_ibptField = value;
                this.RaisePropertyChanged("aliquota_ibpt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliquota_ibptSpecified {
            get {
                return this.aliquota_ibptFieldSpecified;
            }
            set {
                this.aliquota_ibptFieldSpecified = value;
                this.RaisePropertyChanged("aliquota_ibptSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string tipoItem {
            get {
                return this.tipoItemField;
            }
            set {
                this.tipoItemField = value;
                this.RaisePropertyChanged("tipoItem");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cst_pis {
            get {
                return this.cst_pisField;
            }
            set {
                this.cst_pisField = value;
                this.RaisePropertyChanged("cst_pis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliquota_pis {
            get {
                return this.aliquota_pisField;
            }
            set {
                this.aliquota_pisField = value;
                this.RaisePropertyChanged("aliquota_pis");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliquota_pisSpecified {
            get {
                return this.aliquota_pisFieldSpecified;
            }
            set {
                this.aliquota_pisFieldSpecified = value;
                this.RaisePropertyChanged("aliquota_pisSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cst_cofins {
            get {
                return this.cst_cofinsField;
            }
            set {
                this.cst_cofinsField = value;
                this.RaisePropertyChanged("cst_cofins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliquota_cofins {
            get {
                return this.aliquota_cofinsField;
            }
            set {
                this.aliquota_cofinsField = value;
                this.RaisePropertyChanged("aliquota_cofins");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliquota_cofinsSpecified {
            get {
                return this.aliquota_cofinsFieldSpecified;
            }
            set {
                this.aliquota_cofinsFieldSpecified = value;
                this.RaisePropertyChanged("aliquota_cofinsSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string bloqueado {
            get {
                return this.bloqueadoField;
            }
            set {
                this.bloqueadoField = value;
                this.RaisePropertyChanged("bloqueado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string importado_api {
            get {
                return this.importado_apiField;
            }
            set {
                this.importado_apiField = value;
                this.RaisePropertyChanged("importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_familia {
            get {
                return this.codigo_familiaField;
            }
            set {
                this.codigo_familiaField = value;
                this.RaisePropertyChanged("codigo_familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codInt_familia {
            get {
                return this.codInt_familiaField;
            }
            set {
                this.codInt_familiaField = value;
                this.RaisePropertyChanged("codInt_familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao_familia {
            get {
                return this.descricao_familiaField;
            }
            set {
                this.descricao_familiaField = value;
                this.RaisePropertyChanged("descricao_familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string inativo {
            get {
                return this.inativoField;
            }
            set {
                this.inativoField = value;
                this.RaisePropertyChanged("inativo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public dadosIbpt dadosIbpt {
            get {
                return this.dadosIbptField;
            }
            set {
                this.dadosIbptField = value;
                this.RaisePropertyChanged("dadosIbpt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cest {
            get {
                return this.cestField;
            }
            set {
                this.cestField = value;
                this.RaisePropertyChanged("cest");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cfop {
            get {
                return this.cfopField;
            }
            set {
                this.cfopField = value;
                this.RaisePropertyChanged("cfop");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> peso_liq {
            get {
                return this.peso_liqField;
            }
            set {
                this.peso_liqField = value;
                this.RaisePropertyChanged("peso_liq");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool peso_liqSpecified {
            get {
                return this.peso_liqFieldSpecified;
            }
            set {
                this.peso_liqFieldSpecified = value;
                this.RaisePropertyChanged("peso_liqSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> peso_bruto {
            get {
                return this.peso_brutoField;
            }
            set {
                this.peso_brutoField = value;
                this.RaisePropertyChanged("peso_bruto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool peso_brutoSpecified {
            get {
                return this.peso_brutoFieldSpecified;
            }
            set {
                this.peso_brutoFieldSpecified = value;
                this.RaisePropertyChanged("peso_brutoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> estoque_minimo {
            get {
                return this.estoque_minimoField;
            }
            set {
                this.estoque_minimoField = value;
                this.RaisePropertyChanged("estoque_minimo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool estoque_minimoSpecified {
            get {
                return this.estoque_minimoFieldSpecified;
            }
            set {
                this.estoque_minimoFieldSpecified = value;
                this.RaisePropertyChanged("estoque_minimoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descr_detalhada {
            get {
                return this.descr_detalhadaField;
            }
            set {
                this.descr_detalhadaField = value;
                this.RaisePropertyChanged("descr_detalhada");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string obs_internas {
            get {
                return this.obs_internasField;
            }
            set {
                this.obs_internasField = value;
                this.RaisePropertyChanged("obs_internas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class dadosIbpt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<decimal> aliqFederalField;
        
        private bool aliqFederalFieldSpecified;
        
        private System.Nullable<decimal> aliqEstadualField;
        
        private bool aliqEstadualFieldSpecified;
        
        private System.Nullable<decimal> aliqMunicipalField;
        
        private bool aliqMunicipalFieldSpecified;
        
        private string fonteField;
        
        private string chaveField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliqFederal {
            get {
                return this.aliqFederalField;
            }
            set {
                this.aliqFederalField = value;
                this.RaisePropertyChanged("aliqFederal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliqFederalSpecified {
            get {
                return this.aliqFederalFieldSpecified;
            }
            set {
                this.aliqFederalFieldSpecified = value;
                this.RaisePropertyChanged("aliqFederalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliqEstadual {
            get {
                return this.aliqEstadualField;
            }
            set {
                this.aliqEstadualField = value;
                this.RaisePropertyChanged("aliqEstadual");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliqEstadualSpecified {
            get {
                return this.aliqEstadualFieldSpecified;
            }
            set {
                this.aliqEstadualFieldSpecified = value;
                this.RaisePropertyChanged("aliqEstadualSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> aliqMunicipal {
            get {
                return this.aliqMunicipalField;
            }
            set {
                this.aliqMunicipalField = value;
                this.RaisePropertyChanged("aliqMunicipal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool aliqMunicipalSpecified {
            get {
                return this.aliqMunicipalFieldSpecified;
            }
            set {
                this.aliqMunicipalFieldSpecified = value;
                this.RaisePropertyChanged("aliqMunicipalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string fonte {
            get {
                return this.fonteField;
            }
            set {
                this.fonteField = value;
                this.RaisePropertyChanged("fonte");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string chave {
            get {
                return this.chaveField;
            }
            set {
                this.chaveField = value;
                this.RaisePropertyChanged("chave");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_resumido : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_produtoField;
        
        private string codigo_produto_integracaoField;
        
        private string codigoField;
        
        private string descricaoField;
        
        private System.Nullable<decimal> valor_unitarioField;
        
        private bool valor_unitarioFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_produto {
            get {
                return this.codigo_produtoField;
            }
            set {
                this.codigo_produtoField = value;
                this.RaisePropertyChanged("codigo_produto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_produto_integracao {
            get {
                return this.codigo_produto_integracaoField;
            }
            set {
                this.codigo_produto_integracaoField = value;
                this.RaisePropertyChanged("codigo_produto_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao {
            get {
                return this.descricaoField;
            }
            set {
                this.descricaoField = value;
                this.RaisePropertyChanged("descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public System.Nullable<decimal> valor_unitario {
            get {
                return this.valor_unitarioField;
            }
            set {
                this.valor_unitarioField = value;
                this.RaisePropertyChanged("valor_unitario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapIgnoreAttribute()]
        public bool valor_unitarioSpecified {
            get {
                return this.valor_unitarioFieldSpecified;
            }
            set {
                this.valor_unitarioFieldSpecified = value;
                this.RaisePropertyChanged("valor_unitarioSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_list_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private produto_servico_resumido[] produto_servico_resumidoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public produto_servico_resumido[] produto_servico_resumido {
            get {
                return this.produto_servico_resumidoField;
            }
            set {
                this.produto_servico_resumidoField = value;
                this.RaisePropertyChanged("produto_servico_resumido");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_listfull_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private produto_servico_cadastro[] produto_servico_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public produto_servico_cadastro[] produto_servico_cadastro {
            get {
                return this.produto_servico_cadastroField;
            }
            set {
                this.produto_servico_cadastroField = value;
                this.RaisePropertyChanged("produto_servico_cadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_list_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_decrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_hora_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_por_hora_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        private string filtrar_apenas_omiepdvField;
        
        private string filtrar_apenas_familiaField;
        
        private string filtrar_apenas_tipoField;
        
        private string filtrar_apenas_descricaoField;
        
        private string ordem_descrescenteField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_decrescente {
            get {
                return this.ordem_decrescenteField;
            }
            set {
                this.ordem_decrescenteField = value;
                this.RaisePropertyChanged("ordem_decrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_hora_de {
            get {
                return this.filtrar_por_hora_deField;
            }
            set {
                this.filtrar_por_hora_deField = value;
                this.RaisePropertyChanged("filtrar_por_hora_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_hora_ate {
            get {
                return this.filtrar_por_hora_ateField;
            }
            set {
                this.filtrar_por_hora_ateField = value;
                this.RaisePropertyChanged("filtrar_por_hora_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_omiepdv {
            get {
                return this.filtrar_apenas_omiepdvField;
            }
            set {
                this.filtrar_apenas_omiepdvField = value;
                this.RaisePropertyChanged("filtrar_apenas_omiepdv");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_familia {
            get {
                return this.filtrar_apenas_familiaField;
            }
            set {
                this.filtrar_apenas_familiaField = value;
                this.RaisePropertyChanged("filtrar_apenas_familia");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_tipo {
            get {
                return this.filtrar_apenas_tipoField;
            }
            set {
                this.filtrar_apenas_tipoField = value;
                this.RaisePropertyChanged("filtrar_apenas_tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_descricao {
            get {
                return this.filtrar_apenas_descricaoField;
            }
            set {
                this.filtrar_apenas_descricaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_descricao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_lote_response : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loteField;
        
        private string codigo_statusField;
        
        private string descricao_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_status {
            get {
                return this.codigo_statusField;
            }
            set {
                this.codigo_statusField = value;
                this.RaisePropertyChanged("codigo_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao_status {
            get {
                return this.descricao_statusField;
            }
            set {
                this.descricao_statusField = value;
                this.RaisePropertyChanged("descricao_status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_lote_request : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string loteField;
        
        private produto_servico_cadastro[] produto_servico_cadastroField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public produto_servico_cadastro[] produto_servico_cadastro {
            get {
                return this.produto_servico_cadastroField;
            }
            set {
                this.produto_servico_cadastroField = value;
                this.RaisePropertyChanged("produto_servico_cadastro");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_cadastro_chave : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_produtoField;
        
        private string codigo_produto_integracaoField;
        
        private string codigoField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_produto {
            get {
                return this.codigo_produtoField;
            }
            set {
                this.codigo_produtoField = value;
                this.RaisePropertyChanged("codigo_produto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_produto_integracao {
            get {
                return this.codigo_produto_integracaoField;
            }
            set {
                this.codigo_produto_integracaoField = value;
                this.RaisePropertyChanged("codigo_produto_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/produtos/?WSDL")]
    public partial class produto_servico_status : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string codigo_produtoField;
        
        private string codigo_produto_integracaoField;
        
        private string codigo_statusField;
        
        private string descricao_statusField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string codigo_produto {
            get {
                return this.codigo_produtoField;
            }
            set {
                this.codigo_produtoField = value;
                this.RaisePropertyChanged("codigo_produto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_produto_integracao {
            get {
                return this.codigo_produto_integracaoField;
            }
            set {
                this.codigo_produto_integracaoField = value;
                this.RaisePropertyChanged("codigo_produto_integracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string codigo_status {
            get {
                return this.codigo_statusField;
            }
            set {
                this.codigo_statusField = value;
                this.RaisePropertyChanged("codigo_status");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string descricao_status {
            get {
                return this.descricao_statusField;
            }
            set {
                this.descricao_statusField = value;
                this.RaisePropertyChanged("descricao_status");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ProdutosCadastroSoapChannel : Sync.ProdutosCadastroReference.ProdutosCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ProdutosCadastroSoapClient : System.ServiceModel.ClientBase<Sync.ProdutosCadastroReference.ProdutosCadastroSoap>, Sync.ProdutosCadastroReference.ProdutosCadastroSoap {
        
        public ProdutosCadastroSoapClient() {
        }
        
        public ProdutosCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ProdutosCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ProdutosCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_status IncluirProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro) {
            return base.Channel.IncluirProduto(produto_servico_cadastro);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_status AlterarProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro) {
            return base.Channel.AlterarProduto(produto_servico_cadastro);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_status ExcluirProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro_chave produto_servico_cadastro_chave) {
            return base.Channel.ExcluirProduto(produto_servico_cadastro_chave);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_cadastro ConsultarProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro_chave produto_servico_cadastro_chave) {
            return base.Channel.ConsultarProduto(produto_servico_cadastro_chave);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_lote_response IncluirProdutosPorLote(Sync.ProdutosCadastroReference.produto_servico_lote_request produto_servico_lote_request) {
            return base.Channel.IncluirProdutosPorLote(produto_servico_lote_request);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_listfull_response ListarProdutos(Sync.ProdutosCadastroReference.produto_servico_list_request produto_servico_list_request) {
            return base.Channel.ListarProdutos(produto_servico_list_request);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_list_response ListarProdutosResumido(Sync.ProdutosCadastroReference.produto_servico_list_request produto_servico_list_request) {
            return base.Channel.ListarProdutosResumido(produto_servico_list_request);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_status UpsertProduto(Sync.ProdutosCadastroReference.produto_servico_cadastro produto_servico_cadastro) {
            return base.Channel.UpsertProduto(produto_servico_cadastro);
        }
        
        public Sync.ProdutosCadastroReference.produto_servico_lote_response UpsertProdutosPorLote(Sync.ProdutosCadastroReference.produto_servico_lote_request produto_servico_lote_request) {
            return base.Channel.UpsertProdutosPorLote(produto_servico_lote_request);
        }
    }
}
