//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sync.CidadesCadastroReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://app.omie.com.br/api/v1/geral/cidades/?WSDL", ConfigurationName="CidadesCadastroReference.CidadesCadastroSoap")]
    public interface CidadesCadastroSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/cidades/?WSDLPesquisarCidades", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(lista_cidades))]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cidListarResponse")]
        Sync.CidadesCadastroReference.cidListarResponse PesquisarCidades(Sync.CidadesCadastroReference.cidListarRequest cidListarRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://app.omie.com.br/api/v1/geral/cidades/?WSDLPesquisarCidades", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="cidListarResponse")]
        System.Threading.Tasks.Task<Sync.CidadesCadastroReference.cidListarResponse> PesquisarCidadesAsync(Sync.CidadesCadastroReference.cidListarRequest cidListarRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/cidades/?WSDL")]
    public partial class cidListarRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string registros_por_paginaField;
        
        private string apenas_importado_apiField;
        
        private string ordenar_porField;
        
        private string ordem_descrescenteField;
        
        private string filtrar_por_data_deField;
        
        private string filtrar_por_data_ateField;
        
        private string filtrar_apenas_inclusaoField;
        
        private string filtrar_apenas_alteracaoField;
        
        private string filtrar_cidade_contendoField;
        
        private string filtrar_por_ufField;
        
        private string filtrar_por_cidadeField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros_por_pagina {
            get {
                return this.registros_por_paginaField;
            }
            set {
                this.registros_por_paginaField = value;
                this.RaisePropertyChanged("registros_por_pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string apenas_importado_api {
            get {
                return this.apenas_importado_apiField;
            }
            set {
                this.apenas_importado_apiField = value;
                this.RaisePropertyChanged("apenas_importado_api");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordenar_por {
            get {
                return this.ordenar_porField;
            }
            set {
                this.ordenar_porField = value;
                this.RaisePropertyChanged("ordenar_por");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string ordem_descrescente {
            get {
                return this.ordem_descrescenteField;
            }
            set {
                this.ordem_descrescenteField = value;
                this.RaisePropertyChanged("ordem_descrescente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_de {
            get {
                return this.filtrar_por_data_deField;
            }
            set {
                this.filtrar_por_data_deField = value;
                this.RaisePropertyChanged("filtrar_por_data_de");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_data_ate {
            get {
                return this.filtrar_por_data_ateField;
            }
            set {
                this.filtrar_por_data_ateField = value;
                this.RaisePropertyChanged("filtrar_por_data_ate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_inclusao {
            get {
                return this.filtrar_apenas_inclusaoField;
            }
            set {
                this.filtrar_apenas_inclusaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_inclusao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_apenas_alteracao {
            get {
                return this.filtrar_apenas_alteracaoField;
            }
            set {
                this.filtrar_apenas_alteracaoField = value;
                this.RaisePropertyChanged("filtrar_apenas_alteracao");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_cidade_contendo {
            get {
                return this.filtrar_cidade_contendoField;
            }
            set {
                this.filtrar_cidade_contendoField = value;
                this.RaisePropertyChanged("filtrar_cidade_contendo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_uf {
            get {
                return this.filtrar_por_ufField;
            }
            set {
                this.filtrar_por_ufField = value;
                this.RaisePropertyChanged("filtrar_por_uf");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string filtrar_por_cidade {
            get {
                return this.filtrar_por_cidadeField;
            }
            set {
                this.filtrar_por_cidadeField = value;
                this.RaisePropertyChanged("filtrar_por_cidade");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/cidades/?WSDL")]
    public partial class lista_cidades : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string cCodField;
        
        private string cNomeField;
        
        private string cUFField;
        
        private string nCodIBGEField;
        
        private string nCodSIAFIField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cCod {
            get {
                return this.cCodField;
            }
            set {
                this.cCodField = value;
                this.RaisePropertyChanged("cCod");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cNome {
            get {
                return this.cNomeField;
            }
            set {
                this.cNomeField = value;
                this.RaisePropertyChanged("cNome");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string cUF {
            get {
                return this.cUFField;
            }
            set {
                this.cUFField = value;
                this.RaisePropertyChanged("cUF");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public string nCodIBGE {
            get {
                return this.nCodIBGEField;
            }
            set {
                this.nCodIBGEField = value;
                this.RaisePropertyChanged("nCodIBGE");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string nCodSIAFI {
            get {
                return this.nCodSIAFIField;
            }
            set {
                this.nCodSIAFIField = value;
                this.RaisePropertyChanged("nCodSIAFI");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1586.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="http://app.omie.com.br/api/v1/geral/cidades/?WSDL")]
    public partial class cidListarResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string paginaField;
        
        private string total_de_paginasField;
        
        private string registrosField;
        
        private string total_de_registrosField;
        
        private lista_cidades[] lista_cidadesField;
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string pagina {
            get {
                return this.paginaField;
            }
            set {
                this.paginaField = value;
                this.RaisePropertyChanged("pagina");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_paginas {
            get {
                return this.total_de_paginasField;
            }
            set {
                this.total_de_paginasField = value;
                this.RaisePropertyChanged("total_de_paginas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string registros {
            get {
                return this.registrosField;
            }
            set {
                this.registrosField = value;
                this.RaisePropertyChanged("registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(DataType="integer", IsNullable=true)]
        public string total_de_registros {
            get {
                return this.total_de_registrosField;
            }
            set {
                this.total_de_registrosField = value;
                this.RaisePropertyChanged("total_de_registros");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.SoapElementAttribute(IsNullable=true)]
        public lista_cidades[] lista_cidades {
            get {
                return this.lista_cidadesField;
            }
            set {
                this.lista_cidadesField = value;
                this.RaisePropertyChanged("lista_cidades");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CidadesCadastroSoapChannel : Sync.CidadesCadastroReference.CidadesCadastroSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CidadesCadastroSoapClient : System.ServiceModel.ClientBase<Sync.CidadesCadastroReference.CidadesCadastroSoap>, Sync.CidadesCadastroReference.CidadesCadastroSoap {
        
        public CidadesCadastroSoapClient() {
        }
        
        public CidadesCadastroSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CidadesCadastroSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadesCadastroSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CidadesCadastroSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Sync.CidadesCadastroReference.cidListarResponse PesquisarCidades(Sync.CidadesCadastroReference.cidListarRequest cidListarRequest) {
            return base.Channel.PesquisarCidades(cidListarRequest);
        }
        
        public System.Threading.Tasks.Task<Sync.CidadesCadastroReference.cidListarResponse> PesquisarCidadesAsync(Sync.CidadesCadastroReference.cidListarRequest cidListarRequest) {
            return base.Channel.PesquisarCidadesAsync(cidListarRequest);
        }
    }
}
